/* Keyboard bindings and accessible configuration tab, independent of WebGL. */
(() => {
'use strict';
const $=id=>document.getElementById(id), STORAGE='salto-input-bindings-v2';
const ACTIONS={forward:['Avançar','Movimento'],back:['Recuar','Movimento'],left:['Mover à esquerda','Movimento'],right:['Mover à direita','Movimento'],sprint:['Corrida alternativa (segurar)','Movimento'],jump:['Pular','Movimento'],attack:['Ataque leve','Combate'],heavy:['Ataque carregado (segurar / soltar)','Combate'],guard:['Defender / parry (segurar)','Combate'],dodge:['Esquivar / correr (segurar)','Combate'],skill:['Habilidade da classe','Combate'],lock:['Travar / liberar alvo','Combate'],lockKey:['Travar alvo pelo teclado','Combate'],previousTarget:['Alvo anterior','Combate'],nextTarget:['Próximo alvo','Combate'],heal:['Usar frasco','Exploração'],interact:['Interagir / reanimar','Exploração'],cameraLeft:['Olhar à esquerda','Câmera'],cameraRight:['Olhar à direita','Câmera'],cameraUp:['Olhar para cima','Câmera'],cameraDown:['Olhar para baixo','Câmera'],zoomIn:['Aproximar câmera','Câmera'],zoomOut:['Afastar câmera','Câmera'],cameraReset:['Centralizar câmera','Câmera']};
const GLOBAL={pause:['Pausar / continuar','Menus'],controls:['Abrir / fechar Controles','Menus'],confirm:['Começar / continuar aventura','Menus'],sound:['Ativar / silenciar som','Menus']};
const DEFAULTS={p1:{forward:'KeyW',back:'KeyS',left:'KeyA',right:'KeyD',sprint:'ShiftLeft',jump:'KeyF',attack:'Mouse0',heavy:'Shift+Mouse0',guard:'Mouse2',dodge:'Space',skill:'Shift+Mouse2',lock:'Mouse1',lockKey:'KeyQ',previousTarget:'WheelUp',nextTarget:'WheelDown',heal:'KeyR',interact:'KeyE',cameraLeft:'KeyT',cameraRight:'KeyY',cameraUp:'KeyG',cameraDown:'KeyH',zoomIn:'Digit1',zoomOut:'Digit2',cameraReset:'KeyV'},p2:{forward:'ArrowUp',back:'ArrowDown',left:'ArrowLeft',right:'ArrowRight',sprint:'ShiftRight',jump:'KeyN',attack:'KeyU',heavy:'KeyO',guard:'KeyB',dodge:'KeyM',skill:'KeyP',lock:'Backspace',lockKey:'Home',previousTarget:'BracketLeft',nextTarget:'BracketRight',heal:'Delete',interact:'Enter',cameraLeft:'Numpad4',cameraRight:'Numpad6',cameraUp:'Numpad8',cameraDown:'Numpad5',zoomIn:'NumpadAdd',zoomOut:'NumpadSubtract',cameraReset:'End'},global:{pause:'Escape',controls:'F1',confirm:'F3',sound:'F2'}};
const scopes={p1:'Jogador 1',p2:'Jogador 2',global:'Geral'};
const clone=o=>JSON.parse(JSON.stringify(o));
function validCode(code){if(typeof code!=='string')return false;const base=code.replace(/^Shift\+/, '');return /^(Mouse[012]|WheelUp|WheelDown|Key[A-Z]|Digit[0-9]|Numpad([0-9]|Add|Subtract|Multiply|Divide|Decimal|Enter)|Arrow(Up|Down|Left|Right)|Shift(Left|Right)|Control(Left|Right)|Space|Enter|Escape|Backspace|Delete|Insert|Home|End|PageUp|PageDown|BracketLeft|BracketRight|Backslash|Semicolon|Quote|Comma|Period|Slash|Minus|Equal|Backquote|F([1-4]|[6-9]|10))$/.test(base)&&!(code.startsWith('Shift+')&&base.startsWith('Shift'));}
function validMap(map){if(!map||typeof map!=='object')return false;const seen=new Set();for(const scope of Object.keys(DEFAULTS)){if(!map[scope]||Object.keys(map[scope]).length!==Object.keys(DEFAULTS[scope]).length)return false;for(const action of Object.keys(DEFAULTS[scope])){const code=map[scope][action];if(!validCode(code)||seen.has(code)||(scope!=='p1'&&/Mouse|Wheel/.test(code)))return false;seen.add(code);}}return true;}
let bindings=clone(DEFAULTS),open=false,selected='p1',capture=null,swap=null,sensitivity=50,invertY=false,partnerDevice='keyboard';
try{const saved=JSON.parse(localStorage.getItem(STORAGE));if(saved&&saved.version===2&&validMap(saved.bindings)){bindings=clone(saved.bindings);sensitivity=Number.isFinite(saved.sensitivity)?Math.max(1,Math.min(100,saved.sensitivity)):50;invertY=saved.invertY===true;partnerDevice=saved.partnerDevice==='gamepad'?'gamepad':'keyboard';}}catch{}
function keyLabel(code){if(code.startsWith('Shift+'))return 'Shift + '+keyLabel(code.slice(6));const names={Mouse0:'Clique esquerdo',Mouse2:'Clique direito',Mouse1:'Botão central',WheelUp:'Roda ↑',WheelDown:'Roda ↓',Space:'Espaço',Enter:'Enter',Escape:'Esc',Backspace:'Backspace',Delete:'Delete',Insert:'Insert',Home:'Home',End:'End',PageUp:'Page Up',PageDown:'Page Down',ShiftLeft:'Shift esq.',ShiftRight:'Shift dir.',ControlLeft:'Ctrl esq.',ControlRight:'Ctrl dir.',ArrowUp:'↑',ArrowDown:'↓',ArrowLeft:'←',ArrowRight:'→',BracketLeft:'[',BracketRight:']',Backslash:'\\',Semicolon:';',Quote:"'",Comma:',',Period:'.',Slash:'/',Minus:'−',Equal:'=',Backquote:'`',NumpadAdd:'Num +',NumpadSubtract:'Num −',NumpadMultiply:'Num *',NumpadDivide:'Num /',NumpadDecimal:'Num .',NumpadEnter:'Num Enter'};return names[code]||code.replace(/^Key|^Digit/,'').replace(/^Numpad/,'Num ');}
function status(text){$('bindingStatus').textContent=text;}
function binding(scope,action){return bindings[scope][action];}
function label(scope,action){return keyLabel(binding(scope,action));}
function save(){let stored=false;try{localStorage.setItem(STORAGE,JSON.stringify({version:2,bindings,sensitivity,invertY,partnerDevice}));stored=true;}catch{}document.dispatchEvent(new CustomEvent('keyboard-bindings-change'));return stored;}
function clearCapture(){capture=null;swap=null;$('inputCaptureZone').hidden=true;$('cancelBinding').hidden=true;$('swapBinding').hidden=true;}
function focusBinding(scope,action){$('bind-'+scope+'-'+action)?.focus({preventScroll:true});}
function render(){$('deviceOptions').hidden=selected!=='global';$('mouseSensitivity').value=sensitivity;$('sensitivityValue').textContent=sensitivity;$('invertMouseY').checked=invertY;$('coopDeviceSetting').value=partnerDevice;$('partnerDevice').value=partnerDevice;const root=$('bindingList');root.replaceChildren();const source=selected==='global'?GLOBAL:ACTIONS;const groups=new Map();for(const [action,[title,group]] of Object.entries(source)){if(!groups.has(group)){const section=document.createElement('section');section.className='binding-group';const h=document.createElement('h3');h.textContent=group;section.append(h);root.append(section);groups.set(group,section);}const row=document.createElement('div');row.className='binding-row';const text=document.createElement('span');text.textContent=title;const button=document.createElement('button');button.type='button';button.id='bind-'+selected+'-'+action;button.dataset.bindAction=action;button.dataset.bindScope=selected;const listening=capture&&capture.scope===selected&&capture.action===action;button.className='binding-key'+(listening?' listening':'');button.textContent=listening?'Aguardando comando…':label(selected,action);button.setAttribute('aria-label',`${scopes[selected]} · ${title}: ${label(selected,action)}. Alterar comando.`);button.addEventListener('click',()=>{capture={scope:selected,action};swap=null;$('inputCaptureZone').hidden=false;$('cancelBinding').hidden=false;$('swapBinding').hidden=true;status(`Pressione a tecla ou clique na área de captura para ${title.toLowerCase()}. Esc cancela.`);render();focusBinding(selected,action);});row.append(text,button);groups.get(group).append(row);}for(const b of document.querySelectorAll('[data-binding-scope]')){const active=b.dataset.bindingScope===selected;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;}$('bindingsHeading').textContent=scopes[selected];$('bindingsScopePanel').setAttribute('aria-labelledby','scope-'+selected);}
function show(value){if(value===open)return;clearCapture();open=value;$('gamePanel').hidden=open;$('controlsPanel').hidden=!open;for(const [id,active] of [['gameTab',!open],['controlsTab',open]]){const b=$(id);b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;}if(open){render();status('Escolha um comando para configurar teclado ou mouse. As mudanças são salvas automaticamente.');$('controlsTab').focus({preventScroll:true});}document.dispatchEvent(new CustomEvent(open?'keyboard-controls-open':'keyboard-controls-close'));if(!open)$('gameTab').focus({preventScroll:true});}
$('gameTab').addEventListener('click',()=>show(false));$('controlsTab').addEventListener('click',()=>show(true));$('returnGame').addEventListener('click',()=>show(false));
function tabKeyboard(container,selector,handler){container.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.code))return;const buttons=Array.from(container.querySelectorAll(selector));const index=buttons.indexOf(document.activeElement);if(index<0)return;e.preventDefault();const next=e.code==='Home'?0:e.code==='End'?buttons.length-1:(index+(e.code==='ArrowRight'?1:-1)+buttons.length)%buttons.length;handler(buttons[next]);buttons[next].focus();});}
tabKeyboard($('mainTabs'),'[role="tab"]',b=>show(b.id==='controlsTab'));tabKeyboard($('scopeTabs'),'[role="tab"]',b=>{selected=b.dataset.bindingScope;clearCapture();render();});
for(const b of document.querySelectorAll('[data-binding-scope]'))b.addEventListener('click',()=>{selected=b.dataset.bindingScope;clearCapture();render();status('Escolha um comando para editar.');});
$('cancelBinding').addEventListener('click',()=>{const old=capture||swap;clearCapture();render();status('Alteração cancelada.');if(old)focusBinding(old.scope,old.action);});
$('swapBinding').addEventListener('click',()=>{if(!swap)return;const {scope,action,other,code}=swap;const previous=bindings[scope][action];bindings[scope][action]=code;bindings[other.scope][other.action]=previous;clearCapture();const stored=save();render();status(`Teclas trocadas: ${scopes[scope]} · ${(scope==='global'?GLOBAL:ACTIONS)[action][0]} agora usa ${keyLabel(code)}. ${stored?'Salvo neste navegador.':'Aplicado nesta sessão; o navegador não permitiu salvar.'}`);focusBinding(scope,action);});
$('mouseSensitivity').addEventListener('input',()=>{sensitivity=Number($('mouseSensitivity').value);$('sensitivityValue').textContent=sensitivity;save();});
$('invertMouseY').addEventListener('change',()=>{invertY=$('invertMouseY').checked;save();});
function setPartnerDevice(value){partnerDevice=value==='gamepad'?'gamepad':'keyboard';$('coopDeviceSetting').value=partnerDevice;$('partnerDevice').value=partnerDevice;save();}
$('coopDeviceSetting').addEventListener('change',()=>setPartnerDevice($('coopDeviceSetting').value));$('partnerDevice').addEventListener('change',()=>setPartnerDevice($('partnerDevice').value));
$('resetBindings').addEventListener('click',()=>{bindings=clone(DEFAULTS);sensitivity=50,invertY=false,partnerDevice='keyboard';clearCapture();const stored=save();render();status('Atalhos dos dois jogadores e menus restaurados.'+(stored?' Salvo neste navegador.':''));$('resetBindings').focus();});
function assignCaptured(code){if(!capture)return;const {scope,action}=capture;if(!validCode(code)||(scope!=='p1'&&/Mouse|Wheel/.test(code))){status(scope!=='p1'&&/Mouse|Wheel/.test(code)?'O mouse pertence ao Jogador 1. Use uma tecla para este comando.':'Comando reservado do navegador. Escolha outro; Esc cancela.');return;}let other=null;for(const group of Object.keys(bindings))for(const [name,value] of Object.entries(bindings[group]))if(value===code&&(group!==scope||name!==action))other={scope:group,action:name};if(other){swap={scope,action,other,code};capture=null;$('inputCaptureZone').hidden=true;$('cancelBinding').hidden=false;$('swapBinding').hidden=false;render();status(`${keyLabel(code)} já está em ${scopes[other.scope]} · ${(other.scope==='global'?GLOBAL:ACTIONS)[other.action][0]}. Trocar os dois comandos?`);$('swapBinding').focus();return;}bindings[scope][action]=code;clearCapture();const stored=save();render();status(`${(scope==='global'?GLOBAL:ACTIONS)[action][0]}: ${keyLabel(code)}. ${stored?'Salvo neste navegador.':'Aplicado nesta sessão; o navegador não permitiu salvar.'}`);focusBinding(scope,action);}
document.addEventListener('keydown',e=>{if(!capture||e.isComposing)return;e.preventDefault();e.stopImmediatePropagation();if(e.repeat)return;if(e.code==='Escape'){const {scope,action}=capture;clearCapture();render();status('Alteração cancelada.');focusBinding(scope,action);return;}if(e.code.startsWith('Shift')){status('Segure Shift e pressione outro comando, ou solte para usar apenas Shift.');return;}if(e.metaKey||e.altKey){status('Atalho reservado do navegador.');return;}assignCaptured((e.shiftKey?'Shift+':'')+e.code);},true);
document.addEventListener('keyup',e=>{if(capture&&e.code.startsWith('Shift')){e.preventDefault();e.stopImmediatePropagation();assignCaptured(e.code);}},true);
document.addEventListener('mousedown',e=>{if(!capture||!$('inputCaptureZone').contains(e.target))return;e.preventDefault();e.stopImmediatePropagation();assignCaptured((e.shiftKey?'Shift+':'')+'Mouse'+e.button);},true);
document.addEventListener('wheel',e=>{if(!capture||!$('inputCaptureZone').contains(e.target))return;e.preventDefault();e.stopImmediatePropagation();assignCaptured((e.shiftKey?'Shift+':'')+(e.deltaY<0?'WheelUp':'WheelDown'));},{capture:true,passive:false});
$('inputCaptureZone').addEventListener('contextmenu',e=>e.preventDefault());
document.addEventListener('keydown',e=>{if(!open||e.repeat)return;if(e.code===bindings.global.controls||e.code===bindings.global.pause){e.preventDefault();e.stopImmediatePropagation();show(false);}},true);
window.addEventListener('blur',()=>{if(capture){clearCapture();render();status('Captura cancelada ao sair da janela.');}});
window.KeyboardControls={binding,label,keyLabel,actionsForCode(scope,code){return Object.keys(bindings[scope]).filter(action=>bindings[scope][action]===code);},show,get sensitivity(){return .001+sensitivity*.00006;},get invertY(){return invertY;},get partnerDevice(){return partnerDevice;},get isOpen(){return open;},get isCapturing(){return !!capture;},get defaults(){return clone(DEFAULTS);},get bindings(){return clone(bindings);}};
render();
})();
