/* Keyboard bindings and accessible configuration tab, independent of WebGL. */
(() => {
'use strict';
const $=id=>document.getElementById(id), STORAGE='salto-keyboard-bindings-v1';
const ACTIONS={forward:['Avançar','Movimento'],back:['Recuar','Movimento'],left:['Mover à esquerda','Movimento'],right:['Mover à direita','Movimento'],sprint:['Correr (segurar)','Movimento'],jump:['Pular','Movimento'],attack:['Ataque leve','Combate'],heavy:['Ataque carregado (segurar / soltar)','Combate'],guard:['Defender / parry (segurar)','Combate'],dodge:['Esquivar / passo para trás','Combate'],skill:['Habilidade da classe','Combate'],lock:['Travar / liberar alvo','Combate'],previousTarget:['Alvo anterior','Combate'],nextTarget:['Próximo alvo','Combate'],heal:['Usar frasco','Exploração'],interact:['Interagir / reanimar','Exploração'],cameraLeft:['Olhar à esquerda','Câmera'],cameraRight:['Olhar à direita','Câmera'],cameraUp:['Olhar para cima','Câmera'],cameraDown:['Olhar para baixo','Câmera'],zoomIn:['Aproximar câmera','Câmera'],zoomOut:['Afastar câmera','Câmera'],cameraReset:['Centralizar câmera','Câmera']};
const GLOBAL={pause:['Pausar / continuar','Menus'],controls:['Abrir / fechar Controles','Menus'],confirm:['Começar / continuar aventura','Menus'],sound:['Ativar / silenciar som','Menus']};
const DEFAULTS={p1:{forward:'KeyW',back:'KeyS',left:'KeyA',right:'KeyD',sprint:'ShiftLeft',jump:'KeyF',attack:'KeyJ',heavy:'KeyK',guard:'KeyL',dodge:'Space',skill:'KeyC',lock:'KeyQ',previousTarget:'KeyZ',nextTarget:'KeyX',heal:'KeyR',interact:'KeyE',cameraLeft:'KeyT',cameraRight:'KeyY',cameraUp:'KeyG',cameraDown:'KeyH',zoomIn:'Digit1',zoomOut:'Digit2',cameraReset:'KeyV'},p2:{forward:'ArrowUp',back:'ArrowDown',left:'ArrowLeft',right:'ArrowRight',sprint:'ShiftRight',jump:'KeyN',attack:'KeyU',heavy:'KeyO',guard:'KeyB',dodge:'KeyM',skill:'KeyP',lock:'Backspace',previousTarget:'BracketLeft',nextTarget:'BracketRight',heal:'Delete',interact:'Enter',cameraLeft:'Numpad4',cameraRight:'Numpad6',cameraUp:'Numpad8',cameraDown:'Numpad5',zoomIn:'NumpadAdd',zoomOut:'NumpadSubtract',cameraReset:'End'},global:{pause:'Escape',controls:'F1',confirm:'F3',sound:'F2'}};
const scopes={p1:'Jogador 1',p2:'Jogador 2',global:'Geral'};
const clone=o=>JSON.parse(JSON.stringify(o));
function validCode(code){return typeof code==='string'&&/^(Key[A-Z]|Digit[0-9]|Numpad([0-9]|Add|Subtract|Multiply|Divide|Decimal|Enter)|Arrow(Up|Down|Left|Right)|Shift(Left|Right)|Control(Left|Right)|Space|Enter|Escape|Backspace|Delete|Insert|Home|End|PageUp|PageDown|BracketLeft|BracketRight|Backslash|Semicolon|Quote|Comma|Period|Slash|Minus|Equal|Backquote|F([1-4]|[6-9]|10))$/.test(code);}
function validMap(map){if(!map||typeof map!=='object')return false;const seen=new Set();for(const scope of Object.keys(DEFAULTS)){if(!map[scope]||Object.keys(map[scope]).length!==Object.keys(DEFAULTS[scope]).length)return false;for(const action of Object.keys(DEFAULTS[scope])){const code=map[scope][action];if(!validCode(code)||seen.has(code))return false;seen.add(code);}}return true;}
let bindings=clone(DEFAULTS),open=false,selected='p1',capture=null,swap=null,middleMouseLock=true;
try{const saved=JSON.parse(localStorage.getItem(STORAGE));if(saved&&saved.version===1&&validMap(saved.bindings)){bindings=clone(saved.bindings);middleMouseLock=saved.middleMouseLock!==false;}}catch{}
function keyLabel(code){const names={Space:'Espaço',Enter:'Enter',Escape:'Esc',Backspace:'Backspace',Delete:'Delete',Insert:'Insert',Home:'Home',End:'End',PageUp:'Page Up',PageDown:'Page Down',ShiftLeft:'Shift esq.',ShiftRight:'Shift dir.',ControlLeft:'Ctrl esq.',ControlRight:'Ctrl dir.',ArrowUp:'↑',ArrowDown:'↓',ArrowLeft:'←',ArrowRight:'→',BracketLeft:'[',BracketRight:']',Backslash:'\\',Semicolon:';',Quote:"'",Comma:',',Period:'.',Slash:'/',Minus:'−',Equal:'=',Backquote:'`',NumpadAdd:'Num +',NumpadSubtract:'Num −',NumpadMultiply:'Num *',NumpadDivide:'Num /',NumpadDecimal:'Num .',NumpadEnter:'Num Enter'};return names[code]||code.replace(/^Key|^Digit/,'').replace(/^Numpad/,'Num ');}
function status(text){$('bindingStatus').textContent=text;}
function binding(scope,action){return bindings[scope][action];}
function label(scope,action){return keyLabel(binding(scope,action));}
function save(){let stored=false;try{localStorage.setItem(STORAGE,JSON.stringify({version:1,bindings,middleMouseLock}));stored=true;}catch{}document.dispatchEvent(new CustomEvent('keyboard-bindings-change'));return stored;}
function clearCapture(){capture=null;swap=null;$('cancelBinding').hidden=true;$('swapBinding').hidden=true;}
function focusBinding(scope,action){$('bind-'+scope+'-'+action)?.focus({preventScroll:true});}
function render(){$('mouseLockOption').hidden=selected!=='global';$('middleMouseLock').checked=middleMouseLock;const root=$('bindingList');root.replaceChildren();const source=selected==='global'?GLOBAL:ACTIONS;const groups=new Map();for(const [action,[title,group]] of Object.entries(source)){if(!groups.has(group)){const section=document.createElement('section');section.className='binding-group';const h=document.createElement('h3');h.textContent=group;section.append(h);root.append(section);groups.set(group,section);}const row=document.createElement('div');row.className='binding-row';const text=document.createElement('span');text.textContent=title;const button=document.createElement('button');button.type='button';button.id='bind-'+selected+'-'+action;button.dataset.bindAction=action;button.dataset.bindScope=selected;const listening=capture&&capture.scope===selected&&capture.action===action;button.className='binding-key'+(listening?' listening':'');button.textContent=listening?'Pressione uma tecla…':label(selected,action);button.setAttribute('aria-label',`${scopes[selected]} · ${title}: ${label(selected,action)}. Alterar tecla.`);button.addEventListener('click',()=>{capture={scope:selected,action};swap=null;$('cancelBinding').hidden=false;$('swapBinding').hidden=true;status(`Pressione a nova tecla para ${title.toLowerCase()}. Esc cancela.`);render();focusBinding(selected,action);});row.append(text,button);groups.get(group).append(row);}for(const b of document.querySelectorAll('[data-binding-scope]')){const active=b.dataset.bindingScope===selected;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;}$('bindingsHeading').textContent=scopes[selected];$('bindingsScopePanel').setAttribute('aria-labelledby','scope-'+selected);}
function show(value){if(value===open)return;clearCapture();open=value;$('gamePanel').hidden=open;$('controlsPanel').hidden=!open;for(const [id,active] of [['gameTab',!open],['controlsTab',open]]){const b=$(id);b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;}if(open){render();status('Escolha um comando e pressione a nova tecla. As mudanças são salvas automaticamente.');$('controlsTab').focus({preventScroll:true});}document.dispatchEvent(new CustomEvent(open?'keyboard-controls-open':'keyboard-controls-close'));if(!open)$('gameTab').focus({preventScroll:true});}
$('gameTab').addEventListener('click',()=>show(false));$('controlsTab').addEventListener('click',()=>show(true));$('returnGame').addEventListener('click',()=>show(false));
function tabKeyboard(container,selector,handler){container.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.code))return;const buttons=Array.from(container.querySelectorAll(selector));const index=buttons.indexOf(document.activeElement);if(index<0)return;e.preventDefault();const next=e.code==='Home'?0:e.code==='End'?buttons.length-1:(index+(e.code==='ArrowRight'?1:-1)+buttons.length)%buttons.length;handler(buttons[next]);buttons[next].focus();});}
tabKeyboard($('mainTabs'),'[role="tab"]',b=>show(b.id==='controlsTab'));tabKeyboard($('scopeTabs'),'[role="tab"]',b=>{selected=b.dataset.bindingScope;clearCapture();render();});
for(const b of document.querySelectorAll('[data-binding-scope]'))b.addEventListener('click',()=>{selected=b.dataset.bindingScope;clearCapture();render();status('Escolha um comando para editar.');});
$('cancelBinding').addEventListener('click',()=>{const old=capture||swap;clearCapture();render();status('Alteração cancelada.');if(old)focusBinding(old.scope,old.action);});
$('swapBinding').addEventListener('click',()=>{if(!swap)return;const {scope,action,other,code}=swap;const previous=bindings[scope][action];bindings[scope][action]=code;bindings[other.scope][other.action]=previous;clearCapture();const stored=save();render();status(`Teclas trocadas: ${scopes[scope]} · ${(scope==='global'?GLOBAL:ACTIONS)[action][0]} agora usa ${keyLabel(code)}. ${stored?'Salvo neste navegador.':'Aplicado nesta sessão; o navegador não permitiu salvar.'}`);focusBinding(scope,action);});
$('middleMouseLock').addEventListener('change',()=>{middleMouseLock=$('middleMouseLock').checked;save();status(middleMouseLock?'Botão central ativa a trava de alvo do Jogador 1.':'Trava de alvo disponível pelos atalhos de teclado.');});
$('resetBindings').addEventListener('click',()=>{bindings=clone(DEFAULTS);middleMouseLock=true;clearCapture();const stored=save();render();status('Atalhos dos dois jogadores e menus restaurados.'+(stored?' Salvo neste navegador.':''));$('resetBindings').focus();});
document.addEventListener('keydown',e=>{if(!capture)return;if(e.isComposing)return;e.preventDefault();e.stopImmediatePropagation();if(e.repeat)return;const {scope,action}=capture;if(e.code==='Escape'){clearCapture();render();status('Alteração cancelada.');focusBinding(scope,action);return;}if(e.metaKey||e.altKey||!validCode(e.code)){status('Essa tecla é reservada pelo navegador ou pela navegação. Escolha outra; Esc cancela.');return;}let other=null;for(const group of Object.keys(bindings))for(const [name,code] of Object.entries(bindings[group]))if(code===e.code&&(group!==scope||name!==action))other={scope:group,action:name};if(other){swap={scope,action,other,code:e.code};capture=null;$('cancelBinding').hidden=false;$('swapBinding').hidden=false;render();status(`${keyLabel(e.code)} já está em ${scopes[other.scope]} · ${(other.scope==='global'?GLOBAL:ACTIONS)[other.action][0]}. Trocar as duas teclas?`);$('swapBinding').focus();return;}bindings[scope][action]=e.code;clearCapture();const stored=save();render();status(`${(scope==='global'?GLOBAL:ACTIONS)[action][0]}: ${keyLabel(e.code)}. ${stored?'Salvo neste navegador.':'Aplicado nesta sessão; o navegador não permitiu salvar.'}`);focusBinding(scope,action);},true);
document.addEventListener('keydown',e=>{if(!open||e.repeat)return;if(e.code===bindings.global.controls||e.code===bindings.global.pause){e.preventDefault();e.stopImmediatePropagation();show(false);}},true);
window.addEventListener('blur',()=>{if(capture){clearCapture();render();status('Captura cancelada ao sair da janela.');}});
window.KeyboardControls={binding,label,keyLabel,actionsForCode(scope,code){return Object.keys(bindings[scope]).filter(action=>bindings[scope][action]===code);},show,get middleMouseLock(){return middleMouseLock;},get isOpen(){return open;},get isCapturing(){return !!capture;},get defaults(){return clone(DEFAULTS);},get bindings(){return clone(bindings);}};
render();
})();
