/* Salto das Estrelas 3D — original low-poly models; Three.js MIT, bundled locally. */
(() => {
'use strict';
const $ = id => document.getElementById(id), canvas = $('game'), KC=window.KeyboardControls;
const CLASSES = {
 warrior:{name:'Guerreiro',hp:5,speed:6.1,delay:.45,dodge:1.1,color:0xa4dadb,skill:'Redemoinho',cost:35},
 mage:{name:'Mago',hp:3,speed:6,delay:.52,dodge:1.1,color:0xa895f2,skill:'Explosão arcana',cost:40},
 rogue:{name:'Ladrão',hp:3,speed:7.4,delay:.26,dodge:.75,color:0x8bdfb1,skill:'Véu das sombras',cost:30},
 archer:{name:'Arqueiro',hp:4,speed:6.5,delay:.4,dodge:1,color:0xe5bd7c,skill:'Disparo triplo',cost:30}
};
const THEMES = [
 {name:'Jardins do crepúsculo',sky:0x122638,fog:0x183546,stone:0x355265,grass:0x506f69,glow:0x89e6d6,count:7},
 {name:'Bosque das lanternas',sky:0x152630,fog:0x204439,stone:0x374d46,grass:0x52735b,glow:0xd3e597,count:8},
 {name:'Abismo de cristal',sky:0x1e1a37,fog:0x31264a,stone:0x4d4566,grass:0x766397,glow:0xbb9aee,count:8},
 {name:'Cidadela das cinzas',sky:0x291d25,fog:0x442d35,stone:0x60515a,grass:0x876663,glow:0xf6b48b,count:9},
 {name:'Fortaleza do eclipse',sky:0x131b2c,fog:0x243249,stone:0x3e4c62,grass:0x54657e,glow:0x83cce9,count:10}
];
let renderer;
try {
 if (!window.THREE) throw new Error('A biblioteca 3D não foi carregada.');
 renderer = new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});
} catch(error) {
 $('overlayTitle').textContent='O mundo 3D não pôde abrir';$('overlayText').textContent='Ative a aceleração gráfica nas configurações do navegador e recarregue a página. '+error.message;
 $('classPicker').hidden=true;$('classHint').hidden=true;$('overlayButton').disabled=true;return;
}
renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1,1.5));
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new THREE.Scene(), camera=new THREE.PerspectiveCamera(52,1,.1,260);
scene.add(new THREE.HemisphereLight(0xc7e9f4,0x142437,2.2));
const sun=new THREE.DirectionalLight(0xffe5c7,2.8);sun.position.set(-15,30,15);scene.add(sun);
const fill=new THREE.DirectionalLight(0x79b8ff,1.1);fill.position.set(15,8,-15);scene.add(fill);
let world=new THREE.Group();scene.add(world);
const geo={box:new THREE.BoxGeometry(1,1,1),sphere:new THREE.IcosahedronGeometry(1,1),crystal:new THREE.OctahedronGeometry(1),cylinder:new THREE.CylinderGeometry(1,1,1,8),cone:new THREE.ConeGeometry(1,1,7),ring:new THREE.TorusGeometry(1,.035,5,36)};
const materials=new Map();
function material(color,emission=0,opacity=1){const key=`${color}/${emission}/${opacity}`;if(!materials.has(key))materials.set(key,new THREE.MeshStandardMaterial({color,roughness:.8,metalness:.12,emissive:emission,emissiveIntensity:.65,transparent:opacity<1,opacity}));return materials.get(key);}
function mesh(type,color,x,y,z,sx=1,sy=1,sz=1,group=world,glow=0){const m=new THREE.Mesh(geo[type],material(color,glow));m.position.set(x,y,z);m.scale.set(sx,sy,sz);group.add(m);return m;}
const V=THREE.Vector3;
let partner=null,activeProfile=null,coopSelected=false;
const PLAYER_FIELDS=new Set(['selected','hero','level','xp','gold','damage','gear','maxEnergy','energy','maxStamina','stamina','flasks','claimed','rewards','hp','maxHp','shield','jumpBoost','stealth','critical']);
const baseState={mode:'menu',selected:'warrior',hero:null,phase:0,level:1,xp:0,gold:0,lives:3,damage:1,gear:0,maxEnergy:100,energy:100,maxStamina:100,stamina:100,flasks:3,claimed:new Set(),rewards:[],time:0,elapsed:0,checkpoint:{x:0,y:0,z:2},seals:0,shield:0,jumpBoost:0,stealth:0,critical:false};
const S=new Proxy(baseState,{get:(obj,key)=>activeProfile&&PLAYER_FIELDS.has(key)?activeProfile[key]:obj[key],set:(obj,key,value)=>{if(activeProfile&&PLAYER_FIELDS.has(key))activeProfile[key]=value;else obj[key]=value;return true;}});
let floors=[],blocks=[],enemies=[],items=[],objects=[],projectiles=[],effects=[],decor=[],portal=null,boss=null,target=null,toastTime=0,attackCooldown=0,dodgeCooldown=0,skillCooldown=0,animClock=0,yaw=0,cameraDistance=12,shake=0,pitch=.58,lockMarker=null,staminaDelay=0,guardHeld=false,guardTime=0,guardBreak=0,healTime=0,pendingAttack=null,comboIndex=0,comboWindow=0,heavyCharge=null,queuedAction=null,evadeHeld=false,evadeTime=0,evadeSprinted=false,padMove=new V();
let keys=new Set();const heldInputs=new Map();let mouseCaptured=false,mouseDragging=false,mouseFallback=false,padPrev=[],padIndex=null,padConnected=false,padMustRelease=false;let audio=null,sound=true;try{sound=localStorage.getItem('salto3d-sound')!=='off';}catch{}
function soundNote(freq=300,duration=.1,type='sine'){if(!sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.5,audio.currentTime+duration);g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function notify(text,seconds=3){$('gameMessage').textContent=(S.coop?(activeProfile?'J2 · ':'J1 · '):'')+text;toastTime=seconds;}
function distance(a,b){return Math.hypot(a.x-b.x,a.z-b.z);}
function position(a){return a.rig ? a.rig.position : a.position || a;}
function floorAt(x,z,y=Infinity){let top=-Infinity;for(const p of floors)if(Math.abs(x-p.x)<p.w/2 && Math.abs(z-p.z)<p.d/2 && p.y<=y+.05)top=Math.max(top,p.y);return top;}
function platform(x,z,w,d,y=0){floors.push({x,z,w,d,y});mesh('box',THEMES[S.phase].stone,x,y-.9,z,w,1.8,d);mesh('box',THEMES[S.phase].grass,x,y-.045,z,w+.02,.12,d+.02);mesh('cone',THEMES[S.phase].stone,x,y-3.1,z,w*.48,4.5,d*.48).rotation.z=Math.PI;}
function obstacle(x,z,w,d,h){const m=mesh('box',THEMES[S.phase].stone,x,h/2,z,w,h,d);blocks.push({x,z,w,d,h,y:0});return m;}
function actor(type,color,size=1){const rig=new THREE.Group();world.add(rig);const shadow=mesh('sphere',0x041017,0,.025,0,.55,.035,.5,rig);shadow.material=material(0x041017,0,.35);const visual=new THREE.Group();rig.add(visual);const body=mesh('box',color,0,1.05,0,.65,.8,.42,visual);const head=mesh('sphere',0xc9c4b8,0,1.75,0,.28,.3,.28,visual);const hood=mesh('box',color,0,1.86,-.07,.58,.25,.48,visual);mesh('box',0x172638,0,1.73,.25,.42,.1,.08,visual);
 const leftArm=new THREE.Group(),rightArm=new THREE.Group();leftArm.position.set(-.44,1.4,0);rightArm.position.set(.44,1.4,0);visual.add(leftArm,rightArm);mesh('box',color,0,-.28,0,.19,.6,.21,leftArm);mesh('box',color,0,-.28,0,.19,.6,.21,rightArm);
 const leftLeg=new THREE.Group(),rightLeg=new THREE.Group();leftLeg.position.set(-.2,.73,0);rightLeg.position.set(.2,.73,0);visual.add(leftLeg,rightLeg);mesh('box',0x233444,0,-.35,0,.23,.7,.25,leftLeg);mesh('box',0x233444,0,-.35,0,.23,.7,.25,rightLeg);
 const cape=mesh('box',color,0,.95,-.3,.65,.8,.07,visual);cape.rotation.x=.2;
 const weapon=new THREE.Group();rightArm.add(weapon);weapon.position.set(0,-.48,.12);
 if(type==='mage'||type==='spitter'){mesh('cylinder',0x775c54,0,.2,.2,.05,1.7,.05,weapon);mesh('crystal',0xc6a0ff,0,1.1,.2,.2,.28,.2,weapon,0xaa77ff);mesh('cone',color,0,2.2,-.02,.43,.75,.43,visual);}
 else if(type==='archer'){const b=mesh('ring',0xcfa478,0,.2,.2,.42,.65,.42,weapon);b.rotation.y=Math.PI/2;mesh('cylinder',0xe9e1c4,0,.2,.2,.012,1.2,.012,weapon);}
 else{mesh('box',0xd3e8ed,0,-.1,.46,.12,.08,type==='rogue'?.62:1.1,weapon,0x345566);mesh('box',0xd5b478,0,-.1,.1,.38,.08,.09,weapon);if(type==='rogue')mesh('box',0xd3e8ed,0,-.4,.3,.1,.08,.6,leftArm);}
 rig.scale.setScalar(size);return {rig,visual,body,velocity:new V(),walkBlend:0,walkPhase:0,motion:null,leftArm,rightArm,leftLeg,rightLeg,head,cape,weapon,attackAnim:0,moving:false,type};}
function turnActor(a,angle,dt){a.rig.rotation.y+=Math.atan2(Math.sin(angle-a.rig.rotation.y),Math.cos(angle-a.rig.rotation.y))*(1-Math.exp(-dt*18));}
function animateActor(a,t,dt){
 const blend=1-Math.exp(-dt*18);a.walkBlend+=((a.moving?1:0)-a.walkBlend)*blend;a.walkPhase+=dt*(a.sprinting?15:10);const swing=Math.sin(a.walkPhase)*.65*a.walkBlend;
 let lx=swing,rx=-swing,la=-swing*.5,ra=swing*.5,rz=0,lz=0,twist=0,lean=a.sprinting?.16:0;
 a.attackAnim=Math.max(0,a.attackAnim-dt);
 const m=a.motion;
 if(m){m.elapsed+=dt;const u=Math.min(1,m.elapsed/m.duration),hit=Math.sin(Math.PI*u),sweep=Math.sin((u-.25)*Math.PI*1.6),sign=m.combo===2?-1:1;
  if(a.type==='warrior'){ra=m.heavy?-2.1+hit*2.3:-1.15+hit*.7;rz=m.heavy?-hit*.35:sign*sweep*1.35;twist=sign*sweep*.42;la=m.heavy?ra*.65:-hit*.4;lean=hit*.16;if(!m.heavy&&m.combo===3){ra=-1.5*hit;rz=-.2*hit;twist=-.15*hit;lean=hit*.3;}}
  else if(a.type==='rogue'){ra=-hit*1.5;la=-hit*(m.combo===2?1.65:.55);rz=sign*sweep*1.1;lz=-sign*sweep*(m.combo===3?1.1:.5);twist=sign*sweep*.5;lean=hit*.24;}
  else if(a.type==='mage'){ra=-1.9+hit*.65;la=-hit*1.2;rz=sign*sweep*.6;twist=sign*hit*.24;lean=-hit*.1;}
  else if(a.type==='archer'){ra=-1.45-(m.combo===2?.25:0);la=-1.5+hit*(m.combo===3?.95:.65);rz=-.45-hit*.25;lz=.45;twist=hit*(m.combo===3?.4:.25);}
  if(u>=1)a.motion=null;
 }else if(a.charging){const pulse=Math.sin(t*16)*.035;ra=a.type==='archer'?-1.5:-2.1+pulse;la=a.type==='rogue'?-1.8:a.type==='mage'?-1.2:-.9;rz=-.35;twist=-.24;lean=-.1;}
 else if(a.attackAnim>0){ra=-1.1;rz=-Math.sin(a.attackAnim*16)*1.2;}
 else if(a.state==='windup'){ra=-1.9;la=-.5;lean=-.15;}
 if(a.guarding){la=-1.3;ra=-.9;}if(a.healing)ra=-1.65;
 a.leftLeg.rotation.x+=(lx-a.leftLeg.rotation.x)*blend;a.rightLeg.rotation.x+=(rx-a.rightLeg.rotation.x)*blend;
 a.leftArm.rotation.x+=(la-a.leftArm.rotation.x)*blend;a.rightArm.rotation.x+=(ra-a.rightArm.rotation.x)*blend;
 a.leftArm.rotation.z+=(lz-a.leftArm.rotation.z)*blend;a.rightArm.rotation.z+=(rz-a.rightArm.rotation.z)*blend;
 a.visual.rotation.y+=(twist-a.visual.rotation.y)*blend;a.visual.rotation.x+=(lean-a.visual.rotation.x)*blend;
 a.visual.position.y=(Math.abs(Math.sin(a.walkPhase))*.06*a.walkBlend)+Math.sin(t*2)*.015*(1-a.walkBlend);
 a.cape.rotation.x+=(.2+a.walkBlend*.22+Math.sin(t*4)*.06-a.cape.rotation.x)*blend;
}
function addEnemy(type,x,z,y,id,elite=false){const hp=Math.ceil(((type==='sentinel'?4:2)+Math.floor(S.phase/2)+(elite?2:0))*(S.coop?1.6:1));const a=actor(type,type==='sentinel'?0x977869:type==='spitter'?0x896297:0x667d8e,elite?1.15:1);a.rig.position.set(x,y,z);a.rig.rotation.y=Math.PI;a.id=id;a.kind=type;a.maxHp=a.hp=hp;a.alive=true;a.elite=elite;a.anchor={x,y,z};a.state='idle';a.timer=0;a.cooldown=.6;a.stun=0;a.speed=type==='stalker'?4.2+S.phase*.25:2.5;a.dir=new V();a.seal=elite;a.guard=null;
 a.warning=mesh('ring',0xfc7d76,0,.04,0,2,2,2,a.rig,0xee6655);a.warning.rotation.x=Math.PI/2;a.warning.visible=false;
 a.hpBack=mesh('box',0x25323c,0,2.6,0,1,.07,.07,a.rig);a.hpFill=mesh('box',0xef9b91,0,2.61,.04,1,.065,.065,a.rig);enemies.push(a);return a;}
function addItem(kind,x,y,z,value=1){const color=kind==='coin'?0xf1c777:kind==='shield'?0x81d7ee:kind==='jump'?0xbba5ff:0xe990a4;const m=mesh('crystal',color,x,y+.65,z,kind==='coin'?.2:.38,kind==='coin'?.3:.45,kind==='coin'?.2:.38,world,color);items.push({kind,mesh:m,x,y:y+.65,z,value,taken:false,base:y+.65});}
function addObject(kind,x,z,y=0,guard=null){const g=new THREE.Group();g.position.set(x,y,z);world.add(g);const o={kind,x,y,z,mesh:g,used:false,guard,bridges:[]};objects.push(o);
 if(kind==='chest'){mesh('box',0x765741,0,.4,0,1.1,.7,.7,g);mesh('box',0xe1b967,0,.45,.37,.18,.8,.06,g,0x665122);mesh('box',0xd7b468,0,.8,0,1.2,.09,.75,g);}
 if(kind==='crate'){mesh('box',0x786452,0,.5,0,1,1,1,g);for(const x of [-.4,.4])mesh('box',0xac9473,x,.5,.52,.08,1.02,.04,g);}
 if(kind==='lever'){mesh('cylinder',0x68828a,0,.2,0,.45,.4,.45,g);const h=mesh('box',0xd4b777,0,.7,0,.1,1,.1,g);h.rotation.z=.4;mesh('sphere',0xf4bf7c,-.2,1.1,0,.14,.14,.14,g,0xae7822);o.handle=h;}
 if(kind==='shrine'||kind==='checkpoint'){mesh('cylinder',0x577e82,0,.14,0,.8,.28,.8,g);mesh('crystal',kind==='shrine'?0x86dfc6:0x80c8f0,0,1.3,0,.35,.8,.35,g,0x459d9d);mesh('ring',0x98d8d1,0,1.4,0,.7,.7,.7,g,0x397a8a);}
 if(kind==='sign'){mesh('box',0x82705b,0,.8,0,.14,1.6,.14,g);mesh('box',0x476870,0,1.45,0,1.25,.65,.15,g);}
 if(['chest','crate','shrine','checkpoint'].includes(kind))blocks.push({x,z,y,w:kind==='chest'?1.2:kind==='crate'?1:1.6,d:kind==='chest'?.75:kind==='crate'?1:1.6,h:kind==='crate'?1:kind==='chest'?.845:.28,owner:o});return o;}
function tree(x,z,y=0,seed=0){const g=new THREE.Group();g.position.set(x,y,z);world.add(g);blocks.push({x,z,y,w:.46,d:.46,h:3.6});mesh('cylinder',0x34484b,0,1.8,0,.23,3.6,.23,g);for(let k=0;k<3;k++){const branch=mesh('box',0x34484b,Math.sin(k*2+seed)*.6,2+k*.4,Math.cos(k*2+seed)*.6,.16,2,.16,g);branch.rotation.z=.6+k*.6;}mesh('sphere',THEMES[S.phase].grass,0,3.5,0,1.6,1.5,1.3,g);mesh('sphere',THEMES[S.phase].grass,1,2.7,.6,.9,.8,1,g);}
function particles(x,y,z,color,count=12){for(let i=0;i<count;i++){const m=mesh('sphere',color,x,y,z,.065,.065,.065,world,color);effects.push({mesh:m,life:.6,max:.6,velocity:new V((Math.random()-.5)*5,Math.random()*4,(Math.random()-.5)*5),kind:'particle'});}}
function burst(x,y,z,color,radius=3){const m=mesh('ring',color,x,y+.15,z,.1,.1,.1,world,color);m.rotation.x=Math.PI/2;effects.push({mesh:m,life:.5,max:.5,radius,kind:'ring'});}
function loadPhase(index){S.phase=index;scene.remove(world);world=new THREE.Group();scene.add(world);floors=[];blocks=[];enemies=[];objects=[];items=[];projectiles=[];effects=[];decor=[];portal=null;boss=null;S.seals=0;target=null;clearInput();S.stamina=S.maxStamina;S.flasks=3;healTime=0;pendingAttack=null;guardBreak=0;staminaDelay=0;S.checkpoint={x:0,y:0,z:2};S.shield=S.jumpBoost=S.stealth=0;S.critical=false;const th=THEMES[index];scene.background=new THREE.Color(th.sky);scene.fog=new THREE.FogExp2(th.fog,.0105);
 const eliteIndices=[2,Math.floor(th.count/2),th.count-1];
 for(let i=0;i<th.count;i++){
  const x=i===0?0:Math.sin(i*1.8)*2.5,z=-i*20;platform(x,z,16,18);for(let k=0;k<5;k++)addItem('coin',x+Math.sin(k+i)*2,0,z+6-k*3);
  for(let side of [-1,1]){if((i+side)%2===0)tree(x+side*6,z-4,0,i);const pillar=obstacle(x+side*6,z+5,1.1,1.1,3.8+(i%3));mesh('box',th.grass,pillar.position.x,pillar.scale.y+.1,pillar.position.z,1.6,.25,1.6);blocks.push({x:pillar.position.x,z:pillar.position.z,y:pillar.scale.y-.025,w:1.6,d:1.6,h:.25});mesh('crystal',th.glow,x+side*6,1,z-7,.18,.6,.18,world,th.glow);}
  if(i>0){addEnemy(i%3===0?'spitter':'stalker',x-3,z+1,0,`${index}:${i}:a`);if(i>2)addEnemy('stalker',x+3,z-4,0,`${index}:${i}:b`);}
  if(eliteIndices.includes(i)){const e=addEnemy('sentinel',x,z-3,0,`${index}:${i}:elite`,true);mesh('ring',th.glow,x,.08,z-3,2.1,2.1,2.1,world,th.glow).rotation.x=Math.PI/2;e.rig.add(mesh('crystal',0xf5d590,0,2.9,0,.14,.2,.14,new THREE.Group(),0xffd088));}
  if(i===0){addObject('sign',-3,4);addObject('crate',3,-4);addObject('crate',4,-5.5);}
  if(i===3||i===6)addObject('checkpoint',x-4,z+5);
  if(i===Math.floor(th.count/2)-1)addObject('shrine',x+4,z+5);
  if(i===1||i===th.count-2){const side=i===1?1:-1;const lever=addObject('lever',x+side*5.6,z);lever.bridges.push({x:x+side*10,z,w:5,d:3,y:0});platform(x+side*14,z,5,7);platform(x+side*16,z-5,4,4,1.25);platform(x+side*14,z-9,4,4,2.5);platform(x+side*10,z-12,5,5,3.6);const guard=addEnemy('sentinel',x+side*10,z-12,3.6,`${index}:${i}:chest`);guard.seal=false;const chest=addObject('chest',x+side*10,z-13.3,3.6,guard);chest.tier=index+1;addItem(i===1?'shield':'jump',x+side*16,1.25,z-5);}
 }
 const endZ=-(th.count-1)*20;portal=new THREE.Group();portal.position.set(Math.sin((th.count-1)*1.8)*2.5,0,endZ-6);world.add(portal);mesh('cylinder',th.stone,0,.12,0,2,.24,2,portal);for(let k=0;k<2;k++){const m=mesh('ring',th.glow,0,2.1,0,1.7,2,1.7,portal,th.glow);m.rotation.y=k*Math.PI/2;decor.push({mesh:m,kind:'portal',speed:k===0?.25:-.18});}mesh('sphere',th.glow,0,2.1,0,.7,1.1,.7,portal,th.glow);
 if(index===4){boss=addEnemy('sentinel',portal.position.x,endZ+2,0,'boss');boss.kind='boss';boss.rig.scale.setScalar(2);boss.hp=boss.maxHp=S.coop?58:36;boss.speed=3.2;boss.seal=false;boss.rig.children.filter(m=>m.isMesh).forEach(m=>{if(m===boss.head)return;});boss.cooldown=2;}
 // Distant floating ruins and a celestial eclipse belong to the same 3D scene.
 for(let i=0;i<24;i++){const z=18-i*8,x=(i%2?1:-1)*(25+i%5*7);mesh('box',th.stone,x,-4-i%4,z,8+i%5,3,10);mesh('cone',th.stone,x,-9-i%4,z,5,9,6).rotation.z=Math.PI;mesh('box',th.stone,x,0,z,1,7,1);}
 const moon=mesh('sphere',0xc6decb,-32,37,endZ-60,9,9,9,world,0x688ea3);moon.material.fog=false;if(index===4){mesh('sphere',0x111b2b,-30.5,38,endZ-49,8.3,8.3,8.3);const ring=mesh('ring',th.glow,-32,37,endZ-48,9.5,9.5,9.5,world,th.glow);ring.rotation.x=.2;}
 for(let i=0;i<75;i++){const m=mesh('sphere',th.glow,(Math.random()-.5)*65,Math.random()*13+2,15-Math.random()*(th.count*20+30),.035,.035,.035,world,th.glow);decor.push({mesh:m,kind:'mote',base:m.position.y,offset:Math.random()*6});}
 const h=actor(S.selected,CLASSES[S.selected].color);h.rig.position.set(0,0,4);h.rig.rotation.y=Math.PI;h.weapon.scale.setScalar(1+S.gear*.09);h.vy=0;h.grounded=true;h.invuln=1;h.dodgeTime=0;h.dodgeDir=new V(0,0,-1);h.downed=false;h.safePosition=h.rig.position.clone();S.hero=h;if(partner){h.rig.position.x=-1.2;partner.hero=actor(partner.selected,CLASSES[partner.selected].color);const ph=partner.hero;ph.rig.position.set(1.2,0,4);ph.rig.rotation.y=Math.PI;mesh('ring',0x7eb6f6,0,.06,0,.65,.65,.65,ph.rig,0x558ee6).rotation.x=Math.PI/2;mesh('ring',0xa8e9cd,0,.06,0,.65,.65,.65,h.rig,0x668e77).rotation.x=Math.PI/2;ph.weapon.scale.setScalar(1+partner.gear*.09);Object.assign(ph,{vy:0,grounded:true,invuln:1,dodgeTime:0,dodgeDir:new V(0,0,-1),downed:false,safePosition:ph.rig.position.clone()});partner.context=freshContext();partner.stamina=partner.maxStamina;partner.energy=partner.maxEnergy;partner.hp=partner.maxHp;partner.flasks=3;partner.shield=partner.jumpBoost=partner.stealth=0;partner.critical=false;}lockMarker=mesh('ring',0xffe6a1,0,0,0,.48,.48,.48,world,0xd6b86e);lockMarker.visible=false;camera.position.set(10,8,16);yaw=0;pitch=.58;attackCooldown=dodgeCooldown=skillCooldown=0;updateHud();
}
function updateHud(){updateMouseStatus();const c=CLASSES[S.selected],h=S.hero;$('levelLabel').textContent=`0${S.phase+1} / 05`;$('areaLabel').textContent=THEMES[S.phase].name;$('sealLabel').textContent=`Guardiões ${S.seals} / 3`;$('classLabel').textContent=`${c.name} · Nível ${S.level}`;$('hpLabel').textContent=`${S.hp}/${S.maxHp} HP`;$('hpBar').style.width=`${Math.max(0,S.hp/S.maxHp*100)}%`;$('energyBar').style.width=`${S.energy/S.maxEnergy*100}%`;$('xpBar').style.width=`${S.level===15?100:S.xp/xpNeeded()*100}%`;$('xpLabel').textContent=S.level===15?'Nível máximo':`${S.xp}/${xpNeeded()} XP`;$('coinLabel').textContent=`${S.gold} moedas · Equipamento ${S.gear===0?'de treino':`+${S.gear}`}`;$('livesLabel').textContent=`${'♥ '.repeat(S.lives)} · tentativas`;$('powerLabel').textContent=[S.shield>0?`Escudo ${Math.ceil(S.shield)}s`:'',S.jumpBoost>0?`Salto ${Math.ceil(S.jumpBoost)}s`:'',S.stealth>0?'Oculto':''].filter(Boolean).join(' · ');$('abilityLabel').textContent=S.level<3?'Poder no nível 3':skillCooldown>0?`${c.skill}: ${Math.ceil(skillCooldown)}s`:`${currentKey('skill')} · ${c.skill}`;$('bossHud').hidden=!(boss&&boss.alive&&distance(h.rig.position,boss.rig.position)<25);if(boss)$('bossBar').style.width=`${boss.hp/boss.maxHp*100}%`;$('staminaBar').style.width=`${S.stamina/S.maxStamina*100}%`;$('staminaLabel').textContent=heavyCharge?`Carregando ${Math.round(heavyCharge.time/1.1*100)}% · solte ${currentKey('heavy')}`:`Stamina ${Math.floor(S.stamina)}/${S.maxStamina} · ${S.flasks} frascos${comboWindow>0&&comboIndex?' · Combo '+comboIndex+'/3':''}`;$('targetLabel').textContent=validTarget()?`Alvo: ${target.kind==='boss'?'Guardião do Eclipse':target.kind==='sentinel'?'Sentinela':target.kind==='spitter'?'Atirador':'Caçador'} · ${target.hp}/${target.maxHp} HP`:`${currentKey('lock')} · travar alvo`;updatePartnerHud();}
function xpNeeded(){return 60+(S.level-1)*35;}
function awardXP(amount,id){if(S.claimed.has(id))return false;S.claimed.add(id);S.gold+=id==='boss'?100:8+S.phase*2;S.xp+=amount;while(S.level<15&&S.xp>=xpNeeded()){S.xp-=xpNeeded();S.level++;let reward;if([2,7,10,13].includes(S.level)){S.maxHp++;reward='+1 de vida máxima';}else if([4,8,12].includes(S.level)){S.damage++;reward='+1 de dano';}else if(S.level===3)reward=`${CLASSES[S.selected].skill} desbloqueado · ${currentKey('skill')}`;else if(S.level===5)reward='Recarga da esquiva −20%';else if(S.level===9)reward='Recarga da habilidade −20%';else{S.maxEnergy+=20;reward='+20 de energia máxima';}S.hp=Math.min(S.maxHp,S.hp+2);S.energy=S.maxEnergy;S.rewards.push(reward);notify(`Nível ${S.level}! ${reward}`,4);burst(S.hero.rig.position.x,.1,S.hero.rig.position.z,0xffd68a,4);soundNote(650,.25);}if(S.level===15)S.xp=0;return true;}
function startAdventure(){partner=null;Object.assign(S,{mode:'playing',phase:0,level:1,xp:0,gold:0,lives:3,damage:1,gear:0,maxEnergy:100,energy:100,maxStamina:100,stamina:100,flasks:3,claimed:new Set(),rewards:[],elapsed:0});S.hp=S.maxHp=CLASSES[S.selected].hp;S.coop=coopSelected;if(S.coop)partner=createPartner($('partnerClass').value);loadPhase(0);document.body.classList.toggle('coop-active',!!partner);$('overlay').hidden=true;$('playHud').hidden=false;canvas.focus({preventScroll:true});captureMouse();notify(`Derrote os três guardiões. ${currentKey('interact')} interage. ${KC.label('global','controls')} abre Controles.`,4);soundNote(400,.2);}
function overlay(title,text,button,mode){S.mode=mode;clearAllInput();releaseMouse();$('overlay').hidden=false;$('classPicker').hidden=mode!=='menu';$('classHint').hidden=mode!=='menu';$('modePicker').hidden=mode!=='menu';$('coopOptions').hidden=mode!=='menu'||!coopSelected;$('overlayEyebrow').textContent=mode==='paused'?'UM INSTANTE ENTRE BATALHAS':mode==='won'?'O ECLIPSE CHEGOU AO FIM':'A AVENTURA CONTINUA';$('overlayTitle').textContent=title;$('overlayText').textContent=text;$('overlayButton').innerHTML=button+' <span>→</span>';}
function damagePlayer(amount=1,source=null){const h=S.hero;if(S.mode!=='playing'||h.downed||h.invuln>0||h.dodgeTime>0||S.shield>0)return;
 const origin=source?(source.rig?source.rig.position:source.position):null,p=h.rig.position;
 if(isGuarding()&&origin&&new V(Math.sin(h.rig.rotation.y),0,Math.cos(h.rig.rotation.y)).dot(new V(origin.x-p.x,0,origin.z-p.z).normalize())>.15){
  const parry=guardTime<=.18&&source.rig&&source.kind!=='boss',cost=parry?10:22*amount;
  if(S.stamina>=cost){spendStamina(cost);h.invuln=.16;particles(p.x,p.y+1,p.z,0xb4e3e9,8);soundNote(700,.1,'triangle');if(parry){source.stun=1;source.state='recover';source.timer=1;source.warning.visible=false;notify('Parry! Contra-ataque agora.',1.5);}return;}
  S.stamina=0;staminaDelay=.9;guardBreak=1.1;guardHeld=false;notify('Guarda quebrada!');
 }
 healTime=0;pendingAttack=null;cancelCharge();queuedAction=null;comboWindow=0;h.motion=null;h.reviveTarget=null;S.hp-=amount;h.invuln=1.05;shake=.3;particles(p.x,p.y+1,p.z,0xe59c9b);soundNote(120,.18,'sawtooth');if(S.hp<=0)loseLife();}
function loseLife(){if(S.mode!=='playing')return;if(partner){downPlayer();return;}S.lives--;if(S.lives<=0){S.hp=0;overlay('A luz ainda espera.',`Você chegou à fase ${S.phase+1}, nível ${S.level}. Escolha uma classe e tente uma nova aventura.`,'Escolher classe','lost');return;}const h=S.hero;h.rig.position.set(S.checkpoint.x,S.checkpoint.y,S.checkpoint.z);h.vy=0;h.grounded=true;h.invuln=2;h.dodgeTime=0;S.hp=S.maxHp;S.energy=S.maxEnergy;S.stamina=S.maxStamina;S.flasks=3;healTime=0;pendingAttack=null;target=null;clearInput();projectiles.forEach(p=>world.remove(p.mesh));projectiles=[];for(const e of enemies)if(e.alive){e.rig.position.set(e.anchor.x,e.anchor.y,e.anchor.z);e.state='idle';e.timer=0;e.cooldown=1;e.warning.visible=false;if(e.kind==='boss')e.hp=e.maxHp;}camera.position.copy(h.rig.position).add(new V(0,8,12));notify('Retorno ao checkpoint. XP e equipamento preservados.',3);}
function enemyHit(e,damage,source='melee'){if(!e.alive||e.stun>0)return false;const p=S.hero.rig.position,ep=e.rig.position;const toHero=new V(p.x-ep.x,0,p.z-ep.z).normalize(),forward=new V(Math.sin(e.rig.rotation.y),0,Math.cos(e.rig.rotation.y));if(e.kind==='sentinel'&&e.state!=='recover'&&e.state!=='windup'&&source!=='magic'&&source!=='skill'&&source!=='heavy'&&forward.dot(toHero)>.35){particles(ep.x,ep.y+1,ep.z,0xb4ddeb,4);notify('Guarda frontal! Contorne ou ataque após a investida.',1.4);return false;}e.hp-=damage;e.stun=source==='heavy'&&e.kind!=='boss'?.5:.22;if(source==='heavy'&&e.kind!=='boss'){e.state='recover';e.timer=.85;e.warning.visible=false;}e.attackAnim=.2;particles(ep.x,ep.y+1,ep.z,0xefc8a0,8);e.hpFill.scale.x=Math.max(0,e.hp/e.maxHp);soundNote(240,.09,'triangle');if(e.hp<=0){e.alive=false;e.rig.visible=false;if(e.seal){S.seals++;burst(ep.x,ep.y,ep.z,0xffd685,4);notify(`Guardião derrotado · ${S.seals}/3 selos liberados`,3);}partyAwardXP(e.kind==='boss'?250:e.elite?60:25+S.phase*5,e.id);if(e.kind==='boss')notify('O Guardião caiu. O portal final está aberto!',4);}return true;}
function nearestEnemy(range,front=true){let best=null,dist=range;const h=S.hero,p=h.rig.position,fwd=new V(Math.sin(h.rig.rotation.y),0,Math.cos(h.rig.rotation.y));for(const e of enemies){const ep=e.rig.position,d=distance(p,ep);if(!e.alive||Math.abs(p.y-ep.y)>2.3||d>dist)continue;const dot=fwd.dot(new V(ep.x-p.x,0,ep.z-p.z).normalize());if(front&&dot<-.1&&d>2.4)continue;best=e;dist=d;}return best;}
function faceEnemy(e){if(e){const p=S.hero.rig.position;S.hero.rig.rotation.y=Math.atan2(e.rig.position.x-p.x,e.rig.position.z-p.z);}}
function shoot(x,y,z,dir,owner,damage=1,magic=false,speed=18){const color=owner==='enemy'?0xef897f:magic?0xb898ff:0xffd38c;const m=mesh(magic||owner==='enemy'?'sphere':'box',color,x,y,z,magic?.16:.055,magic?.16:.055,magic?.16:.55,world,color);m.rotation.y=Math.atan2(dir.x,dir.z);projectiles.push({mesh:m,dir:dir.clone().normalize(),speed,owner,damage,magic,origin:{x,y,z},player:activeProfile||baseState,life:2.5});}
function combatReady(){return S.mode==='playing'&&!S.hero.downed&&!S.hero.reviveTarget&&attackCooldown<=0&&!pendingAttack&&healTime<=0&&guardBreak<=0&&S.hero.dodgeTime<=0;}
function attack(heavy=false,power=0,deposit=0){
 if(!combatReady()||heavyCharge)return false;
 const c=CLASSES[S.selected],cost=S.selected==='mage'?(heavy?18:10):S.selected==='archer'?(heavy?9:5):0,stamina=heavy?32+12*power:S.selected==='rogue'?12:18;
 if(S.energy<cost){notify('Sem energia. Aguarde a recuperação.',1);return false;}if(!spendStamina(stamina-deposit))return false;
 S.energy-=cost;comboIndex=heavy?0:comboWindow>0?comboIndex%3+1:1;comboWindow=heavy?0:1.15;
 attackCooldown=heavy?Math.max(.65,c.delay*1.5):c.delay*(comboIndex===3?1.12:.9);
 const duration=attackCooldown;S.hero.motion={heavy,power,combo:comboIndex,elapsed:0,duration};S.hero.attackAnim=0;guardHeld=false;
 if(validTarget())faceEnemy(target);
 pendingAttack={time:heavy?.22:S.selected==='rogue'?.075:.12,heavy,power,combo:comboIndex};return true;
}
function beginHeavyCharge(){if(!combatReady()||heavyCharge||S.stamina<32)return false;const cost=S.selected==='mage'?18:S.selected==='archer'?9:0;if(S.energy<cost)return false;if(!spendStamina(8))return false;guardHeld=false;comboWindow=0;comboIndex=0;heavyCharge={time:0};S.hero.charging=true;return true;}
function releaseHeavyCharge(){if(!heavyCharge)return false;const power=Math.min(1,heavyCharge.time/1.1);heavyCharge=null;S.hero.charging=false;const available=Math.min(power,Math.max(0,(S.stamina-24)/12));return attack(true,available,8);}
function cancelCharge(){heavyCharge=null;if(S.hero)S.hero.charging=false;}
function requestCombat(name){let ok=false;if(name==='attack')ok=attack();if(name==='heavy')ok=beginHeavyCharge();if(name==='dodge')ok=dodge();if(name==='skill')ok=useSkill();if(!ok&&(pendingAttack||attackCooldown>0||S.hero.dodgeTime>0)&&healTime<=0&&guardBreak<=0)queuedAction={name,time:.42};else if(ok)queuedAction=null;}
function strike(heavy,power=0,combo=0){const h=S.hero,p=h.rig.position,ranged=S.selected==='mage'||S.selected==='archer',enemy=validTarget()?target:null;if(enemy)faceEnemy(enemy);const dir=new V(Math.sin(h.rig.rotation.y),0,Math.cos(h.rig.rotation.y)),damage=(S.damage+S.gear)*(heavy?2+1.5*power:combo===3?1.5:1);
 if(ranged){let aim=dir;if(enemy){const ep=enemy.rig.position;aim=new V(ep.x-p.x,ep.y-p.y,ep.z-p.z).normalize();}shoot(p.x+dir.x*.7,p.y+1.2,p.z+dir.z*.7,aim,'hero',damage,S.selected==='mage',heavy?24+6*power:18+combo*1.2);}
 else{burst(p.x+dir.x,p.y,p.z+dir.z,heavy?0xffd59e:0xbce4df,heavy?3.2+power:combo===3?3.2:2.6);for(const e of enemies){if(e.alive&&distance(p,e.rig.position)<(heavy?3.8:S.selected==='warrior'?3.3:2.6)&&Math.abs(p.y-e.rig.position.y)<2.2){const dot=dir.dot(new V(e.rig.position.x-p.x,0,e.rig.position.z-p.z).normalize());if(dot>-.05){const hit=enemyHit(e,damage*(S.critical?2:1),heavy?'heavy':'melee');if(hit&&combo===3&&e.kind!=='boss'){e.stun=.35;}if(hit&&S.critical){S.critical=false;S.stealth=0;}}}}for(const b of projectiles)if(b.owner==='enemy'&&distance(p,b.mesh.position)<3&&Math.abs(p.y+1-b.mesh.position.y)<2)b.life=0;}
 for(const o of objects)if(o.kind==='crate'&&!o.used&&distance(p,o)<3&&Math.abs(p.y-o.y)<2){o.used=true;o.mesh.visible=false;S.gold+=4;S.energy=Math.min(S.maxEnergy,S.energy+10);particles(o.x,o.y+.5,o.z,0xc5a979);}if(heavy&&power>.8){shake=.16;particles(p.x+dir.x,p.y+1,p.z+dir.z,CLASSES[S.selected].color,16);}soundNote(ranged?560:heavy?130:190,.09,'triangle');}
function useSkill(){if(heavyCharge)return false;if(S.mode!=='playing'||S.hero.downed||S.hero.reviveTarget||healTime>0||pendingAttack||guardBreak>0||S.hero.dodgeTime>0||attackCooldown>.1)return;if(S.level<3){notify('Habilidade desbloqueada no nível 3.',2);return;}if(skillCooldown>0)return;const c=CLASSES[S.selected],h=S.hero,p=h.rig.position;if(S.energy<c.cost){notify(`A habilidade precisa de ${c.cost} de energia.`,2);return;}if(!spendStamina(22))return;guardHeld=false;S.energy-=c.cost;attackCooldown=.5;skillCooldown=(S.level>=9?6.4:8);h.attackAnim=.5;const damage=(S.damage+S.gear)*2;
 if(S.selected==='rogue'){S.stealth=4;S.critical=true;h.invuln=.8;notify('Oculto por 4s · próximo golpe crítico');}
 else if(S.selected==='archer'){const e=validTarget()?target:null;if(e)faceEnemy(e);const angle=h.rig.rotation.y;for(const delta of [-.17,0,.17]){const d=new V(Math.sin(angle+delta),0,Math.cos(angle+delta));shoot(p.x,p.y+1.2,p.z,d,'hero',damage,false,23);}}
 else{const radius=S.selected==='mage'?7:4.8;burst(p.x,p.y,p.z,c.color,radius);for(const e of enemies)if(e.alive&&distance(p,e.rig.position)<radius&&Math.abs(p.y-e.rig.position.y)<3)enemyHit(e,damage,'skill');particles(p.x,p.y+1,p.z,c.color,24);}soundNote(740,.3);return true;}
function moveInput(){let x=(keys.has('right')?1:0)-(keys.has('left')?1:0)+padMove.x,z=(keys.has('back')?1:0)-(keys.has('forward')?1:0)+padMove.z;const length=Math.hypot(x,z);if(length>1){x/=length;z/=length;}return new V(x*Math.cos(yaw)+z*Math.sin(yaw),0,-x*Math.sin(yaw)+z*Math.cos(yaw));}
function beginEvade(){if(S.mode!=='playing'||S.hero.downed)return;evadeHeld=true;evadeTime=0;evadeSprinted=false;}
function endEvade(){if(!evadeHeld)return;const shouldDodge=!evadeSprinted&&S.mode==='playing';evadeHeld=false;evadeTime=0;evadeSprinted=false;if(shouldDodge)requestCombat('dodge');}
function dodge(){if(S.mode!=='playing'||S.hero.downed||S.hero.reviveTarget||dodgeCooldown>0||pendingAttack||attackCooldown>.12||guardBreak>0||!S.hero.grounded)return;if(!spendStamina(25))return;healTime=0;cancelCharge();queuedAction=null;comboWindow=0;const h=S.hero;h.motion=null;h.dodgeDir=moveInput();if(h.dodgeDir.lengthSq()===0)h.dodgeDir.set(-Math.sin(h.rig.rotation.y),0,-Math.cos(h.rig.rotation.y));h.dodgeTime=.27;h.invuln=Math.max(h.invuln,.3);guardHeld=false;dodgeCooldown=CLASSES[S.selected].dodge*(S.level>=5?.8:1);burst(h.rig.position.x,h.rig.position.y,h.rig.position.z,0x8cdecd,2);soundNote(220,.1);return true;}
function jump(){const h=S.hero;if(S.mode!=='playing'||h.downed||h.reviveTarget||!h.grounded||heavyCharge||healTime>0||pendingAttack||guardBreak>0||h.dodgeTime>0)return;if(!spendStamina(8))return;h.vy=S.jumpBoost>0?13:10.5;h.grounded=false;soundNote(330,.08);}
function interact(){if(S.mode!=='playing'||S.hero.downed)return;if(beginRevive())return;const p=S.hero.rig.position;const candidates=objects.filter(o=>!o.used&&o.kind!=='crate'&&o.kind!=='checkpoint'&&distance(p,o)<2.8&&Math.abs(p.y-o.y)<2);candidates.sort((a,b)=>distance(p,a)-distance(p,b));const o=candidates[0];if(!o)return;
 if(o.kind==='sign'){notify(`Salte os vãos. ${currentKey('interact')} abre pontes. A guarda cede após a investida.`,5);return;}
 if(o.kind==='lever'){o.used=true;o.handle.rotation.z=-.5;for(const b of o.bridges){platform(b.x,b.z,b.w,b.d,b.y);mesh('box',0x86b7a8,b.x,b.y+.01,b.z,b.w,.08,.1);}notify('Ponte lateral aberta. Equipamento no alto das ruínas.');}
 if(o.kind==='chest'){if(o.guard.alive){notify('Baú selado. Derrote o sentinela da plataforma.',2);return;}o.used=true;o.mesh.rotation.x=-.18;S.gear=Math.max(S.gear,o.tier);S.hero.weapon.scale.setScalar(1+S.gear*.09);S.gold+=25;S.maxEnergy+=5;S.energy=S.maxEnergy;particles(o.x,o.y+1,o.z,0xffd17e,22);notify(`Equipamento +${S.gear} · +25 moedas · +5 energia máxima`,4);}
 if(o.kind==='shrine'){if(S.gold<30){notify('O santuário precisa de 30 moedas.',2);return;}o.used=true;S.gold-=30;S.hp=S.maxHp;S.energy=S.maxEnergy;S.flasks=3;notify('Santuário: vida e energia restauradas.');burst(o.x,o.y,o.z,0x9af1ca,4);}soundNote(480,.18);}
// Solid map volumes share one representation across actors, projectiles and camera.
let solidCache=[],solidFloorRef=null,solidBlockRef=null,solidCount=-1;
function solidBoxes(){const count=floors.length+blocks.length;if(floors!==solidFloorRef||blocks!==solidBlockRef||count!==solidCount){solidFloorRef=floors;solidBlockRef=blocks;solidCount=count;solidCache=blocks.map(b=>({x:b.x,z:b.z,w:b.w,d:b.d,bottom:b.y||0,top:(b.y||0)+b.h,owner:b.owner})).concat(floors.map(f=>({x:f.x,z:f.z,w:f.w,d:f.d,bottom:f.y-1.8,top:f.y})));}return solidCache.filter(b=>!b.owner||b.owner.kind!=='crate'||!b.owner.used);}
function overlapsCircle(x,z,b,radius){const cx=THREE.MathUtils.clamp(x,b.x-b.w/2,b.x+b.w/2),cz=THREE.MathUtils.clamp(z,b.z-b.d/2,b.z+b.d/2);return (x-cx)**2+(z-cz)**2<radius**2;}
function blocked(x,z,y,radius=.34,height=1.95){return solidBoxes().some(b=>y<b.top-.003&&y+height>b.bottom+.003&&overlapsCircle(x,z,b,radius));}
function moveCapsule(pos,dx,dz,radius=.34,height=1.95){const boxes=solidBoxes().filter(b=>pos.y<b.top-.003&&pos.y+height>b.bottom+.003),steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/(radius*.45)));const sx=dx/steps,sz=dz/steps;
 for(let step=0;step<steps;step++){pos.x+=sx;pos.z+=sz;for(let pass=0;pass<3;pass++){let pushed=false;for(const b of boxes){const minX=b.x-b.w/2,maxX=b.x+b.w/2,minZ=b.z-b.d/2,maxZ=b.z+b.d/2,cx=THREE.MathUtils.clamp(pos.x,minX,maxX),cz=THREE.MathUtils.clamp(pos.z,minZ,maxZ),vx=pos.x-cx,vz=pos.z-cz,dist=Math.hypot(vx,vz);if(dist>=radius-.00001)continue;if(dist>.00001){const push=(radius-dist+.0001)/dist;pos.x+=vx*push;pos.z+=vz*push;}else{const edges=[{d:pos.x-minX,x:minX-radius-.0001,z:pos.z},{d:maxX-pos.x,x:maxX+radius+.0001,z:pos.z},{d:pos.z-minZ,x:pos.x,z:minZ-radius-.0001},{d:maxZ-pos.z,x:pos.x,z:maxZ+radius+.0001}];edges.sort((a,b)=>a.d-b.d);pos.x=edges[0].x;pos.z=edges[0].z;}pushed=true;}if(!pushed)break;}}
}
function moveVertical(h,dt){const pos=h.rig.position,oldY=pos.y,height=1.95;h.vy-=25*dt;let nextY=oldY+h.vy*dt;h.grounded=false;const boxes=solidBoxes();if(h.vy<=0){let top=-Infinity;for(const b of boxes)if(oldY>=b.top-.05&&nextY<=b.top&&overlapsCircle(pos.x,pos.z,b,.24))top=Math.max(top,b.top);if(Number.isFinite(top)){nextY=top;h.vy=0;h.grounded=true;}}else{let ceiling=Infinity;for(const b of boxes)if(oldY+height<=b.bottom+.005&&nextY+height>=b.bottom&&overlapsCircle(pos.x,pos.z,b,.3))ceiling=Math.min(ceiling,b.bottom);if(Number.isFinite(ceiling)){nextY=ceiling-height;h.vy=0;}}pos.y=nextY;}
function segmentHit(from,to,radius=.05){let first=1;for(const b of solidBoxes()){const mins=[b.x-b.w/2-radius,b.bottom-radius,b.z-b.d/2-radius],maxs=[b.x+b.w/2+radius,b.top+radius,b.z+b.d/2+radius],a=[from.x,from.y,from.z],v=[to.x-from.x,to.y-from.y,to.z-from.z];let lo=0,hi=1;for(let i=0;i<3;i++){if(Math.abs(v[i])<1e-8){if(a[i]<mins[i]||a[i]>maxs[i]){hi=-1;break;}}else{let near=(mins[i]-a[i])/v[i],far=(maxs[i]-a[i])/v[i];if(near>far)[near,far]=[far,near];lo=Math.max(lo,near);hi=Math.min(hi,far);if(lo>hi)break;}}if(lo<=hi&&hi>=0&&lo<=1)first=Math.min(first,Math.max(0,lo));}return first;}
function segmentBodyHit(from,to,actor,radius=.65){const center=actor.rig.position.clone().add(new V(0,actor.kind==='boss'?2:1.15,0)),line=to.clone().sub(from),length=line.lengthSq(),t=length?THREE.MathUtils.clamp(center.clone().sub(from).dot(line)/length,0,1):0;return from.clone().addScaledVector(line,t).distanceTo(center)<radius;}
function updateHero(dt){const h=S.hero,p=h.rig.position;if(h.downed){h.rig.visible=true;h.rig.rotation.z=1.1;return;}h.invuln=Math.max(0,h.invuln-dt);h.dodgeTime=Math.max(0,h.dodgeTime-dt);updateCombat(dt);let dir=moveInput(),speed=CLASSES[S.selected].speed;h.moving=dir.lengthSq()>0;if(evadeHeld)evadeTime+=dt;const sprint=keys.has('sprint')||(evadeHeld&&evadeTime>=.22);h.sprinting=sprint&&h.moving&&h.grounded&&S.stamina>1&&!isGuarding()&&!heavyCharge&&attackCooldown<=0&&healTime<=0&&guardBreak<=0;if(h.sprinting){if(evadeHeld)evadeSprinted=true;speed*=1.55;S.stamina=Math.max(0,S.stamina-18*dt);staminaDelay=.6;}if(isGuarding())speed*=.45;if(attackCooldown>0)speed*=.65;if(heavyCharge)speed*=.35;if(healTime>0||guardBreak>0)speed*=.15;if(h.dodgeTime>0){dir=h.dodgeDir;speed=16;}if(h.reviveTarget){speed=0;h.moving=false;}if(validTarget())turnActor(h,Math.atan2(target.rig.position.x-p.x,target.rig.position.z-p.z),dt);else if(!activeProfile||KC.partnerDevice==='gamepad')turnActor(h,yaw+Math.PI,dt);else if(h.moving)turnActor(h,Math.atan2(dir.x,dir.z),dt);if(partner){const other=(activeProfile?baseState:partner).hero.rig.position,next={x:p.x+dir.x*speed*dt,z:p.z+dir.z*speed*dt};if(distance(next,other)>20&&distance(next,other)>distance(p,other))speed=0;}const desiredVelocity=dir.clone().multiplyScalar(speed);if(h.dodgeTime>0)h.velocity.copy(desiredVelocity);else h.velocity.lerp(desiredVelocity,1-Math.exp(-dt*24));if(speed===0)h.velocity.set(0,0,0);moveCapsule(p,h.velocity.x*dt,h.velocity.z*dt);
 moveVertical(h,dt);if(p.y<-15){loseLife();return;}h.rig.visible=true;if(h.grounded)h.safePosition=p.clone();h.cape.visible=S.stealth<=0||Math.floor(S.stealth*10)%2===0;h.guarding=isGuarding();h.healing=healTime>0;animateActor(h,animClock,dt);if(h.dodgeTime>0){h.rig.rotation.x=-Math.sin(h.dodgeTime/.27*Math.PI)*.95;}else h.rig.rotation.x=0;
 for(const item of items){if(item.taken)continue;item.mesh.rotation.y+=dt;item.mesh.position.y=item.base+Math.sin(animClock*2+item.z)*.15;if(distance(p,item)<1.05&&Math.abs(p.y+.8-item.mesh.position.y)<1.5){item.taken=true;item.mesh.visible=false;if(item.kind==='coin')S.gold+=item.value;else if(item.kind==='shield'){S.shield=10;notify('Escudo ativo por 10s');}else if(item.kind==='jump'){S.jumpBoost=12;notify('Super salto ativo por 12s');}soundNote(630,.05);}}
 for(const o of objects)if(o.kind==='checkpoint'&&!o.used&&distance(p,o)<2&&Math.abs(p.y-o.y)<1){o.used=true;S.checkpoint={x:o.x,y:o.y,z:o.z};S.hp=Math.min(S.maxHp,S.hp+1);burst(o.x,o.y,o.z,0x9ddfea,3);notify('Checkpoint ativado · +1 HP');}
 const downedFriend=partner&&(activeProfile?baseState:partner).hero;const nearby=objects.find(o=>!o.used&&!['crate','checkpoint'].includes(o.kind)&&distance(p,o)<2.8&&Math.abs(p.y-o.y)<2);if(!activeProfile){$('interactionLabel').hidden=!nearby&&!((downedFriend&&downedFriend.downed)&&distance(p,downedFriend.rig.position)<2.8);if(downedFriend&&downedFriend.downed&&distance(p,downedFriend.rig.position)<2.8)$('interactionLabel').textContent=`${currentKey('interact')} · Reanimar parceiro (2s)`;}if(nearby&&!activeProfile)$('interactionLabel').textContent=`${currentKey('interact')} · ${nearby.kind==='chest'?'Abrir baú':nearby.kind==='shrine'?'Curar · 30 moedas':nearby.kind==='lever'?'Abrir ponte':'Ler placa'}`;
 if(!partner)checkPortal();
}
function checkPortal(){const p=baseState.hero.rig.position; if((distance(p,portal.position)<2.1||(partner&&distance(partner.hero.rig.position,portal.position)<2.1))&&Math.abs(p.y)<2){if(partner&&(partner.hero.downed||baseState.hero.downed||distance(partner.hero.rig.position,portal.position)>8||distance(baseState.hero.rig.position,portal.position)>8)){if(toastTime<=0)notify('Os dois jogadores precisam chegar ao portal.',2);}else if(S.seals<3){if(toastTime<=0)notify(`O portal exige os três guardiões: ${S.seals}/3`,2);}else if(boss&&boss.alive){if(toastTime<=0)notify('Derrote o Guardião do Eclipse para abrir o portal.',2);}else if(S.phase===4){const seconds=Math.floor(S.elapsed);let record='';try{const key=partner?`salto3d-coop-record-${S.selected}-${partner.selected}`:`salto3d-record-${S.selected}`,old=Number(localStorage.getItem(key));if(!old||seconds<old){localStorage.setItem(key,String(seconds));record=' Novo recorde!';}}catch{}overlay('As estrelas voltaram.',`Você venceu os cinco mundos como ${CLASSES[S.selected].name}${partner?' + '+CLASSES[partner.selected].name:''}, nível ${S.level}${partner?' / '+partner.level:''}, em ${Math.floor(seconds/60)}m ${seconds%60}s.${record}`,'Escolher classe','won');}else{loadPhase(S.phase+1);S.hp=S.maxHp;S.energy=S.maxEnergy;notify(`Novo mundo: ${THEMES[S.phase].name}`,4);}}
}

function updateEnemies(dt){for(const e of enemies){if(!e.alive)continue;const victim=party().filter(p=>!p.hero.downed&&p.stealth<=0).sort((a,b)=>distance(a.hero.rig.position,e.rig.position)-distance(b.hero.rig.position,e.rig.position))[0];if(!victim)continue;const hero=victim.hero.rig.position,p=e.rig.position,d=distance(hero,p),height=Math.abs(hero.y-p.y);e.cooldown=Math.max(0,e.cooldown-dt);e.stun=Math.max(0,e.stun-dt);e.timer-=dt;e.moving=false;e.hpBack.visible=e.hpFill.visible=d<18;if(e.stun>0){animateActor(e,animClock,dt);continue;}const notice=d<(e.kind==='boss'?26:16)&&height<2.6&&victim.stealth<=0;
 if(e.state==='windup'){e.warning.visible=true;e.warning.scale.setScalar((e.kind==='boss'?2.5:1.8)*(1+.08*Math.sin(animClock*24)));if(e.timer<=0){e.warning.visible=false;e.attackAnim=.4;if(e.kind==='spitter'){shoot(p.x,p.y+1.3,p.z,e.dir,'enemy',1,true,8+S.phase);e.state='recover';e.timer=.7;}
 else if(e.kind==='boss'&&e.bossPattern%2===0){for(let a=-2;a<=2;a++){const angle=Math.atan2(e.dir.x,e.dir.z)+a*.28;shoot(p.x,p.y+1.7,p.z,new V(Math.sin(angle),0,Math.cos(angle)),'enemy',1,true,10);}e.state='recover';e.timer=1;}
 else{e.state='charge';e.timer=e.kind==='boss'?.65:.4;e.hit=false;}}
 }else if(e.state==='charge'){e.moving=true;const nx=p.x+e.dir.x*dt*(e.kind==='boss'?14:10),nz=p.z+e.dir.z*dt*(e.kind==='boss'?14:10);if(Number.isFinite(floorAt(nx,nz,p.y))){moveCapsule(p,nx-p.x,nz-p.z,e.kind==='boss'?.8:.36,e.kind==='boss'?3.9:1.95);}if(!e.hit&&distance(hero,p)<(e.kind==='boss'?2.5:1.6)&&height<2){withPlayer(victim,()=>damagePlayer(1,e));e.hit=true;}if(e.timer<=0){e.state='recover';e.timer=e.kind==='boss'?1.1:.85;}}
 else if(e.state==='recover'){if(e.timer<=0){e.state='idle';e.cooldown=e.kind==='boss'?.65:1;}}
 else if(notice){e.rig.rotation.y=Math.atan2(hero.x-p.x,hero.z-p.z);const attackRange=e.kind==='spitter'?12:e.kind==='boss'?12:4.4;if(d<attackRange&&e.cooldown<=0){e.state='windup';e.timer=e.kind==='boss'?(e.hp<e.maxHp/2?.55:.85):e.kind==='spitter'?.85:.65;e.dir.set(hero.x-p.x,0,hero.z-p.z).normalize();e.bossPattern=(e.bossPattern||0)+1;}
 else if(d>(e.kind==='spitter'?7:2.4)){const nx=p.x+Math.sin(e.rig.rotation.y)*e.speed*dt,nz=p.z+Math.cos(e.rig.rotation.y)*e.speed*dt;const floor=floorAt(nx,nz,p.y);if(Number.isFinite(floor)&&Math.abs(floor-p.y)<.3){moveCapsule(p,nx-p.x,nz-p.z,e.kind==='boss'?.8:.36,e.kind==='boss'?3.9:1.95);e.moving=true;}}
 }else{e.rig.rotation.y+=Math.sin(animClock*.4+e.anchor.z)*dt*.2;}animateActor(e,animClock,dt);}}
function updateProjectiles(dt){for(const b of projectiles){b.life-=dt;const from=b.mesh.position.clone(),to=from.clone().addScaledVector(b.dir,b.speed*dt),wall=segmentHit(from,to,.05);const end=from.clone().lerp(to,wall);if(b.life>0){if(b.owner==='enemy'){for(const victim of party())if(!victim.hero.downed&&segmentBodyHit(from,end,victim.hero,.7)){withPlayer(victim,()=>damagePlayer(b.damage,{position:b.origin}));b.life=0;break;}}else{for(const e of enemies)if(e.alive&&segmentBodyHit(from,end,e,e.kind==='boss'?1.65:.7)){withPlayer(b.player,()=>enemyHit(e,b.damage,b.magic?'magic':'arrow'));b.life=0;break;}}}b.mesh.position.copy(end);if(wall<1)b.life=0;}projectiles=projectiles.filter(b=>{if(b.life<=0){world.remove(b.mesh);return false;}return true;});}
function updateEffects(dt){for(const e of effects){e.life-=dt;if(e.kind==='particle'){e.mesh.position.addScaledVector(e.velocity,dt);e.velocity.y-=8*dt;e.mesh.scale.setScalar(.065*Math.max(0,e.life/e.max));}else e.mesh.scale.setScalar((1-e.life/e.max)*e.radius+.1);}effects=effects.filter(e=>{if(e.life<=0){world.remove(e.mesh);return false;}return true;});for(const d of decor)if(d.kind==='mote')d.mesh.position.y=d.base+Math.sin(animClock*.5+d.offset)*.35;else d.mesh.rotation.y+=dt*d.speed;}
function cameraUpdate(dt){const p=S.hero.rig.position;const menu=S.mode==='menu';let desired,look;if(menu){const t=animClock*.05;desired=new V(13+Math.sin(t)*2,10,16);look=new V(0,1,-15);}else{
 if(partner){const other=partner.hero.rig.position,mid=p.clone().add(other).multiplyScalar(.5);look=mid.clone().add(new V(0,1.2,0));const range=Math.min(30,cameraDistance+distance(p,other)*.65),horizontal=Math.cos(pitch)*range;desired=new V(mid.x+Math.sin(yaw)*horizontal,mid.y+Math.sin(pitch)*range,mid.z+Math.cos(yaw)*horizontal);}else{if(validTarget()){const ep=target.rig.position,desiredYaw=Math.atan2(p.x-ep.x,p.z-ep.z);yaw+=Math.atan2(Math.sin(desiredYaw-yaw),Math.cos(desiredYaw-yaw))*(1-Math.exp(-dt*5));look=new V(p.x*.7+ep.x*.3,p.y+1.2,p.z*.7+ep.z*.3);}else look=new V(p.x,p.y+1.2,p.z);
 const horizontal=Math.cos(pitch)*cameraDistance;desired=new V(p.x+Math.sin(yaw)*horizontal,p.y+Math.sin(pitch)*cameraDistance,p.z+Math.cos(yaw)*horizontal);}
 }const cameraWall=segmentHit(look,desired,.22);if(cameraWall<1)desired.lerpVectors(look,desired,Math.max(.03,cameraWall-.025));camera.position.lerp(desired,1-Math.exp(-dt*12));const currentWall=segmentHit(look,camera.position,.18);if(currentWall<1)camera.position.lerpVectors(look,camera.position,Math.max(.03,currentWall-.015));if(shake>0){camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake;}camera.lookAt(look);
 if(lockMarker){lockMarker.visible=S.mode==='playing'&&validTarget();if(lockMarker.visible){lockMarker.position.copy(target.rig.position).add(new V(0,target.kind==='boss'?3.8:2.2,0));lockMarker.quaternion.copy(camera.quaternion);}}
}
let previous=performance.now(),hudClock=0;
function updatePlayer(dt){attackCooldown=Math.max(0,attackCooldown-dt);dodgeCooldown=Math.max(0,dodgeCooldown-dt);skillCooldown=Math.max(0,skillCooldown-dt);S.shield=Math.max(0,S.shield-dt);S.jumpBoost=Math.max(0,S.jumpBoost-dt);S.stealth=Math.max(0,S.stealth-dt);S.energy=Math.min(S.maxEnergy,S.energy+12*dt);if(S.stealth===0)S.critical=false;
 if(!S.hero.downed){if(keys.has('attack')&&!queuedAction)attack();updateKeyboardCamera(dt);updateHero(dt);updateRevive(dt);}else{S.hero.rig.visible=true;S.hero.rig.rotation.z=1.1;}}
function frame(now){const dt=Math.min((now-previous)/1000,.04);previous=now;if(KC.isOpen){requestAnimationFrame(frame);return;}animClock+=S.mode==='paused'?0:dt;if(S.mode==='playing'){S.elapsed+=dt;pollGamepad(dt);updatePlayer(dt);if(partner)withPlayer(partner,()=>updatePlayer(dt));if(S.mode==='playing'){updateEnemies(dt);updateProjectiles(dt);if(partner){updatePartyDowned(dt);if(S.mode==='playing')checkPortal();}}updateEffects(dt);shake=Math.max(0,shake-dt);toastTime-=dt;if(toastTime<=0)$('gameMessage').textContent='';hudClock-=dt;if(hudClock<=0){updateHud();hudClock=.1;}}
 else if(S.mode==='paused'&&!KC.isOpen){pollGamepad(dt);}else if(S.mode==='menu'){updateEffects(dt);animateActor(S.hero,animClock,dt);}cameraUpdate(dt);renderer.render(scene,camera);requestAnimationFrame(frame);}
function resize(){const rect=canvas.parentElement.getBoundingClientRect();if(rect.width<=0||rect.height<=0)return;renderer.setSize(rect.width,rect.height,false);camera.aspect=rect.width/rect.height;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(canvas.parentElement);
function pause(){if(S.mode==='playing')overlay('Sou uma pausa, não o fim.','Respire. A aventura espera por você.','Continuar','paused');else if(S.mode==='paused'){S.mode='playing';$('overlay').hidden=true;canvas.focus({preventScroll:true});captureMouse();}}
function spendStamina(amount){if(S.stamina<amount){if(toastTime<=0)notify('Sem stamina. Recue e recupere o fôlego.',1.2);return false;}S.stamina-=amount;staminaDelay=.65;return true;}
function validTarget(){if(target&&(!target.alive||distance(S.hero.rig.position,target.rig.position)>27||Math.abs(S.hero.rig.position.y-target.rig.position.y)>5))target=null;return !!target;}
function toggleTarget(){if(S.mode!=='playing'||S.hero.downed)return;if(validTarget()){target=null;notify('Alvo liberado',1);return;}target=nearestEnemy(22,false);notify(target?`Alvo travado · ${currentKey('previousTarget')}/${currentKey('nextTarget')} troca o alvo`:'Nenhum alvo próximo',1.5);}
function cycleTarget(direction){if(!validTarget())return;const p=S.hero.rig.position,candidates=enemies.filter(e=>e.alive&&distance(p,e.rig.position)<24&&Math.abs(p.y-e.rig.position.y)<3).sort((a,b)=>Math.atan2(a.rig.position.x-p.x,a.rig.position.z-p.z)-Math.atan2(b.rig.position.x-p.x,b.rig.position.z-p.z));if(candidates.length<2)return;const i=candidates.indexOf(target);target=candidates[(i+direction+candidates.length)%candidates.length];}
function isGuarding(){return !heavyCharge&&guardHeld&&guardBreak<=0&&healTime<=0&&attackCooldown<=0&&S.hero.dodgeTime<=0&&S.hero.grounded;}
function beginGuard(){if(S.mode!=='playing'||S.hero.downed||S.hero.reviveTarget)return;if(!guardHeld)guardTime=0;guardHeld=true;}
function heal(){if(S.mode!=='playing'||S.hero.downed||S.hero.reviveTarget||heavyCharge||healTime>0||pendingAttack||attackCooldown>0||S.hero.dodgeTime>0||guardBreak>0)return;if(S.flasks<=0){notify('Sem frascos. O santuário restaura as cargas.',2);return;}if(S.hp>=S.maxHp){notify('Sua vida já está cheia.',1.5);return;}S.flasks--;healTime=.9;guardHeld=false;notify('Bebendo frasco…',.9);}
function updateCombat(dt){comboWindow=Math.max(0,comboWindow-dt);
 if(heavyCharge){heavyCharge.time=Math.min(1.1,heavyCharge.time+dt);staminaDelay=.65;if(heavyCharge.time>=1.1)releaseHeavyCharge();}
 if(queuedAction){queuedAction.time-=dt;if(queuedAction.time<=0)queuedAction=null;else if(!pendingAttack&&attackCooldown<=0&&S.hero.dodgeTime<=0){const name=queuedAction.name;queuedAction=null;if(name==='heavy'&&!keys.has('heavy'))attack(true);else requestCombat(name);}}
if(keys.has('guard')&&!guardHeld&&attackCooldown<=0&&guardBreak<=0)beginGuard();guardBreak=Math.max(0,guardBreak-dt);staminaDelay=Math.max(0,staminaDelay-dt);if(staminaDelay===0&&!isGuarding())S.stamina=Math.min(S.maxStamina,S.stamina+28*dt);if(guardHeld)guardTime+=dt;
 if(pendingAttack){pendingAttack.time-=dt;if(pendingAttack.time<=0){const {heavy,power,combo}=pendingAttack;pendingAttack=null;strike(heavy,power,combo);}}
 if(healTime>0){healTime-=dt;if(healTime<=0){healTime=0;S.hp=Math.min(S.maxHp,S.hp+3);burst(S.hero.rig.position.x,S.hero.rig.position.y,S.hero.rig.position.z,0x9df3b9,2);notify('Frasco: +3 HP',1.5);}}
 validTarget();}
function clearInput(){keys.clear();guardHeld=false;guardTime=0;cancelCharge();queuedAction=null;comboIndex=0;comboWindow=0;evadeHeld=false;evadeTime=0;evadeSprinted=false;padMove.set(0,0,0);if(S.hero)S.hero.velocity.set(0,0,0);}
function currentKey(action){return KC.label(activeProfile?'p2':'p1',action);}
function action(name){if(name==='jump')jump();if(['attack','heavy','dodge','skill'].includes(name))requestCombat(name);if(name==='interact')interact();if(name==='lock'||name==='lockKey')toggleTarget();if(name==='heal')heal();if(name==='guard')beginGuard();if(name==='previousTarget')cycleTarget(-1);if(name==='nextTarget')cycleTarget(1);if(name==='cameraReset'){yaw=S.hero.rig.rotation.y+Math.PI;pitch=.58;cameraDistance=12;}if(name==='zoomIn')cameraDistance=Math.max(8,cameraDistance-.6);if(name==='zoomOut')cameraDistance=Math.min(18,cameraDistance+.6);if(name==='cameraLeft')rotateCamera(-6,0);if(name==='cameraRight')rotateCamera(6,0);if(name==='cameraUp')rotateCamera(0,-6);if(name==='cameraDown')rotateCamera(0,6);}
function rotateCamera(dx,dy){if(!partner&&validTarget())return;yaw-=dx*.004;pitch=THREE.MathUtils.clamp(pitch+dy*.004,.18,1.08);}
function updateKeyboardCamera(dt){rotateCamera(((keys.has('cameraRight')?1:0)-(keys.has('cameraLeft')?1:0))*dt*260,((keys.has('cameraDown')?1:0)-(keys.has('cameraUp')?1:0))*dt*200);cameraDistance=THREE.MathUtils.clamp(cameraDistance+((keys.has('zoomOut')?1:0)-(keys.has('zoomIn')?1:0))*dt*5,8,18);}
function inputActions(profile,names,down){withPlayer(profile,()=>{for(const name of names){if(!down){keys.delete(name);if(name==='guard')guardHeld=false;if(name==='heavy')releaseHeavyCharge();if(name==='dodge')endEvade();}else{keys.add(name);if(name==='dodge')beginEvade();else action(name);}}});}
function routeInput(code,down,shift=false,repeat=false){if(!down){const held=heldInputs.get(code);if(held){heldInputs.delete(code);inputActions(held.profile,held.actions,false);return true;}return false;}if(heldInputs.has(code)||repeat)return heldInputs.has(code);for(const [scope,profile] of [['p1',baseState],['p2',partner]]){if(!profile||(scope==='p2'&&KC.partnerDevice==='gamepad'))continue;const combo=shift?'Shift+'+code:code;let actions=KC.actionsForCode(scope,combo);if(!actions.length&&combo!==code)actions=KC.actionsForCode(scope,code);if(actions.length){heldInputs.set(code,{profile,actions});inputActions(profile,actions,true);return true;}}return false;}
document.addEventListener('keydown',e=>{if(e.isComposing||KC.isCapturing)return;const general=KC.actionsForCode('global',(e.shiftKey?'Shift+':'')+e.code).concat(e.shiftKey?KC.actionsForCode('global',e.code):[]);if(general.length){e.preventDefault();if(e.repeat)return;for(const name of general){if(name==='controls')KC.show(!KC.isOpen);if(name==='sound')$('soundButton').click();if(!KC.isOpen&&name==='pause')pause();if(!KC.isOpen&&name==='confirm')$('overlayButton').click();}return;}if(KC.isOpen||S.mode!=='playing'||e.target.matches('input,select,textarea')||e.target.closest('button,a,summary')||e.metaKey||e.altKey)return;if(routeInput(e.code,true,e.shiftKey,e.repeat))e.preventDefault();});
document.addEventListener('keyup',e=>routeInput(e.code,false));
function captureMouse(){if(S.mode!=='playing'||KC.isOpen)return;canvas.focus({preventScroll:true});if(document.pointerLockElement===canvas)return;try{const result=canvas.requestPointerLock?.();if(result&&result.then)result.then(()=>{if(KC.isOpen||S.mode!=='playing')releaseMouse();}).catch(()=>mouseUnavailable());else if(!canvas.requestPointerLock)mouseUnavailable();}catch{mouseUnavailable();}}
function releaseMouse(){mouseDragging=false;if(document.pointerLockElement===canvas)document.exitPointerLock();updateMouseStatus();}
function mouseUnavailable(){if(document.pointerLockElement===canvas)return;mouseFallback=true;$('mouseStatus').textContent='Captura indisponível: segure e arraste a cena para olhar.';$('mouseStatus').hidden=S.mode!=='playing';}
function updateMouseStatus(){mouseCaptured=document.pointerLockElement===canvas;$('captureMouse').hidden=S.mode!=='playing'||mouseCaptured||KC.isOpen;$('crosshair').hidden=S.mode!=='playing'||!!target;$('mouseStatus').hidden=S.mode!=='playing'||mouseCaptured;}
document.addEventListener('pointerlockchange',()=>{const was=mouseCaptured;mouseCaptured=document.pointerLockElement===canvas;if(mouseCaptured&&(KC.isOpen||S.mode!=='playing')){document.exitPointerLock();return;}if(mouseCaptured)mouseFallback=false;if(was&&!mouseCaptured&&S.mode==='playing')pause();updateMouseStatus();});document.addEventListener('pointerlockerror',mouseUnavailable);
$('captureMouse').addEventListener('click',captureMouse);
canvas.addEventListener('mousedown',e=>{if(S.mode!=='playing'||KC.isOpen)return;e.preventDefault();canvas.focus({preventScroll:true});if(!mouseCaptured&&!mouseFallback){captureMouse();mouseDragging=true;return;}mouseDragging=!mouseCaptured;routeInput('Mouse'+e.button,true,e.shiftKey);});
document.addEventListener('mouseup',e=>{routeInput('Mouse'+e.button,false);mouseDragging=false;});
document.addEventListener('mousemove',e=>{if(S.mode!=='playing'||KC.isOpen||(!mouseCaptured&&!mouseDragging))return;withPlayer(baseState,()=>rotateCamera(e.movementX*KC.sensitivity/.004,e.movementY*KC.sensitivity/.004*(KC.invertY?-1:1)));});
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{if(S.mode!=='playing'||KC.isOpen)return;e.preventDefault();const code=e.deltaY<0?'WheelUp':'WheelDown';routeInput(code,true,e.shiftKey);routeInput(code,false);},{passive:false});
window.addEventListener('blur',()=>{clearAllInput();if(S.mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&S.mode==='playing')pause();});
document.addEventListener('keyboard-controls-open',()=>{clearAllInput();if(S.mode==='playing')pause();});
document.addEventListener('keyboard-controls-close',()=>{resize();updateHud();if(S.mode==='playing')canvas.focus({preventScroll:true});else $('overlayButton').focus({preventScroll:true});});
document.addEventListener('keyboard-bindings-change',()=>{clearAllInput();updateKeyHints();updateHud();});
function updateKeyHints(){const k=name=>KC.label('p1',name);$('keyboardHints').textContent=`${k('forward')}/${k('left')}/${k('back')}/${k('right')} mover · ${k('attack')} ataque · ${k('heavy')} forte · ${k('guard')} defesa · ${k('dodge')} toque esquiva / segurar corre · ${k('jump')} pula`;$('cameraHints').textContent=`Mouse gira a visão · ${KC.label('global','controls')} Controles`;$('controlsShortcut').textContent=KC.label('global','controls');$('pauseButton').title=`Pausar (${KC.label('global','pause')})`;$('keyboardGuide').textContent=`J1: ${k('forward')}/${k('left')}/${k('back')}/${k('right')} mover, ${k('skill')} habilidade, ${k('lock')} ou ${k('lockKey')} alvo, ${k('previousTarget')}/${k('nextTarget')} troca alvo, ${k('heal')} cura, ${k('interact')} interage. J2 no teclado: setas movem, ${KC.label('p2','attack')} ataca, ${KC.label('p2','heavy')} carrega, ${KC.label('p2','guard')} defende, ${KC.label('p2','dodge')} toque esquiva / segurar corre. ${KC.label('global','confirm')} começa/continua; ${KC.label('global','pause')} pausa e libera o mouse. Câmera livre quando o alvo estiver liberado.`;}
// Each hero keeps its own combat resources and input. The world advances once.
function party(){return partner?[baseState,partner]:[baseState];}
function freshContext(){return {attackCooldown:0,dodgeCooldown:0,skillCooldown:0,staminaDelay:0,guardHeld:false,guardTime:0,guardBreak:0,healTime:0,pendingAttack:null,comboIndex:0,comboWindow:0,heavyCharge:null,queuedAction:null,evadeHeld:false,evadeTime:0,evadeSprinted:false,padMove:new V(),target:null,keys:new Set()};}
function combatContext(){return {attackCooldown,dodgeCooldown,skillCooldown,staminaDelay,guardHeld,guardTime,guardBreak,healTime,pendingAttack,comboIndex,comboWindow,heavyCharge,queuedAction,evadeHeld,evadeTime,evadeSprinted,padMove,target,keys};}
function applyContext(c){({attackCooldown,dodgeCooldown,skillCooldown,staminaDelay,guardHeld,guardTime,guardBreak,healTime,pendingAttack,comboIndex,comboWindow,heavyCharge,queuedAction,evadeHeld,evadeTime,evadeSprinted,padMove,target,keys}=c);}
function withPlayer(profile,fn){const old=activeProfile||baseState;if(!profile||profile===old)return fn();old.context=combatContext();activeProfile=profile===baseState?null:profile;applyContext(profile.context);try{return fn();}finally{profile.context=combatContext();activeProfile=old===baseState?null:old;applyContext(old.context);}}
function createPartner(selected){const p={};for(const key of PLAYER_FIELDS)p[key]=baseState[key];p.selected=selected;p.hp=p.maxHp=CLASSES[selected].hp;p.claimed=new Set();p.rewards=[];p.context=freshContext();return p;}
function clearAllInput(){heldInputs.clear();padMustRelease=true;for(const p of party())withPlayer(p,clearInput);}
function axis(value){const abs=Math.abs(value||0);return abs<.18?0:Math.sign(value)*(Math.min(1,abs)-.18)/.82;}
function applyGamepad(pad,dt){const down=Array.from({length:17},(_,i)=>{const b=pad.buttons[i];return !!b&&(b.pressed||b.value>(i===6||i===7?.55:.5));});if(padMustRelease){padPrev=down;padMove.set(0,0,0);if(!down.some(Boolean)&&Math.abs(pad.axes[0]||0)<.18&&Math.abs(pad.axes[1]||0)<.18)padMustRelease=false;return;}
 padMove.set(axis(pad.axes[0]),0,axis(pad.axes[1]));if(padMove.length()>1)padMove.normalize();
 const map={0:'interact',1:'dodge',2:'heal',3:'jump',4:'guard',5:'attack',6:'skill',7:'heavy',10:'sprint',11:'lock',14:'previousTarget',15:'nextTarget'};
 for(const [i,name] of Object.entries(map)){if(down[i]&&!padPrev[i])inputActions(partner,[name],true);else if(!down[i]&&padPrev[i])inputActions(partner,[name],false);}
 if(down[9]&&!padPrev[9]){padPrev=down;if(S.mode==='playing'||S.mode==='paused')pause();return;}rotateCamera(axis(pad.axes[2])*dt*520,axis(pad.axes[3])*dt*400);padPrev=down;
}
function pollGamepad(dt){if(!partner||KC.partnerDevice!=='gamepad'){padConnected=false;return;}let pads=[];try{pads=Array.from(navigator.getGamepads?.()||[]);}catch{}const pad=pads.find(p=>p&&p.connected&&p.mapping==='standard');if(!pad){if(padConnected){withPlayer(partner,clearInput);padPrev=[];padMustRelease=true;padIndex=null;}padConnected=false;return;}if(!padConnected||padIndex!==pad.index){withPlayer(partner,clearInput);padMustRelease=true;padPrev=[];padIndex=pad.index;}padConnected=true;withPlayer(partner,()=>applyGamepad(pad,dt));}
function partyAwardXP(amount,id){for(const profile of party())withPlayer(profile,()=>{const down=S.hero.downed;awardXP(amount,id);if(down)S.hp=0;});}
function downPlayer(){const h=S.hero;if(h.downed)return;S.hp=0;h.downed=true;h.downTime=20;h.reviveTarget=null;h.dodgeTime=0;h.invuln=0;pendingAttack=null;healTime=0;target=null;if(h.rig.position.y<-5){h.rig.position.copy(h.safePosition||new V(S.checkpoint.x,0,S.checkpoint.z));h.vy=0;}clearInput();notify('Caído! O parceiro tem 20s para reanimar você.',4);}
function beginRevive(){if(!partner)return false;const other=activeProfile?baseState:partner,h=S.hero;if(!other.hero.downed||distance(h.rig.position,other.hero.rig.position)>2.8||Math.abs(h.rig.position.y-other.hero.rig.position.y)>2)return false;if(healTime>0||pendingAttack||attackCooldown>0)return true;h.reviveTarget=other;h.reviveProgress=0;guardHeld=false;notify('Reanimando… fique parado por 2s.',2);return true;}
function updateRevive(dt){const h=S.hero,p=h.reviveTarget;if(!p)return;if(!p.hero.downed||moveInput().lengthSq()>.01||distance(h.rig.position,p.hero.rig.position)>2.8){h.reviveTarget=null;return;}h.reviveProgress+=dt;if(h.reviveProgress>=2){p.hp=Math.max(1,Math.ceil(p.maxHp/2));p.stamina=p.maxStamina;p.hero.downed=false;p.hero.rig.rotation.z=0;p.hero.invuln=1.5;p.hero.downTime=0;h.reviveTarget=null;particles(p.hero.rig.position.x,p.hero.rig.position.y+1,p.hero.rig.position.z,0x9aeece,20);notify('Parceiro reanimado!',3);}}
function updatePartyDowned(dt){if(!partner)return;if(party().every(p=>p.hero.downed)){teamRespawn();return;}for(const p of party())if(p.hero.downed){p.hero.downTime-=dt;if(p.hero.downTime<=0){teamRespawn();return;}}}
function teamRespawn(){S.lives--;if(S.lives<=0){overlay('A equipe caiu.',`Vocês chegaram à fase ${S.phase+1}, níveis ${baseState.level} / ${partner.level}. Escolham suas classes e tentem novamente.`,'Escolher classes','lost');return;}for(const [i,p] of party().entries())withPlayer(p,()=>{const h=S.hero;S.hp=S.maxHp;S.energy=S.maxEnergy;S.stamina=S.maxStamina;S.flasks=3;h.rig.position.set(S.checkpoint.x+(i===0?-1.2:1.2),S.checkpoint.y,S.checkpoint.z);Object.assign(h,{vy:0,grounded:true,invuln:2,dodgeTime:0,downed:false,downTime:0,reviveTarget:null});h.rig.rotation.z=0;h.safePosition=h.rig.position.clone();applyContext(freshContext());});projectiles.forEach(p=>world.remove(p.mesh));projectiles=[];for(const e of enemies)if(e.alive){e.rig.position.set(e.anchor.x,e.anchor.y,e.anchor.z);e.state='idle';e.timer=0;e.cooldown=1;e.warning.visible=false;if(e.kind==='boss')e.hp=e.maxHp;}camera.position.set(S.checkpoint.x,S.checkpoint.y+8,S.checkpoint.z+12);notify('Equipe no checkpoint · progresso preservado.',4);}
function updatePartnerHud(){const hud=$('partnerHud');hud.hidden=!partner;$('coopStatus').hidden=!partner;if(!partner)return;const p=partner;$('partnerClassLabel').textContent=`J2 · ${CLASSES[p.selected].name} · Nv. ${p.level}`;$('partnerHpLabel').textContent=`${p.hp}/${p.maxHp} HP`;$('partnerHpBar').style.width=`${Math.max(0,p.hp/p.maxHp*100)}%`;$('partnerStaminaBar').style.width=`${p.stamina/p.maxStamina*100}%`;$('partnerEnergyBar').style.width=`${p.energy/p.maxEnergy*100}%`;$('partnerXpBar').style.width=`${p.level===15?100:p.xp/(60+(p.level-1)*35)*100}%`;$('partnerResources').textContent=`${p.gold} moedas · Equip. +${p.gear} · ${p.flasks} frascos`;$('partnerStatus').textContent=p.hero.downed?`CAÍDO · ${Math.ceil(p.hero.downTime)}s para reanimar`:p.hero.reviveTarget?'Reanimando parceiro…':p.context.heavyCharge?`Carregando ${Math.round(p.context.heavyCharge.time/1.1*100)}% · solte ${KC.label('p2','heavy')}`:`${p.context.target&&p.context.target.alive?'Alvo travado · ':''}${Math.floor(p.stamina)} stamina · ${p.xp} XP`;$('coopStatus').textContent=`COOP LOCAL · J1: ${KC.label('p1','forward')}/${KC.label('p1','left')}/${KC.label('p1','back')}/${KC.label('p1','right')} · J2: ${KC.label('p2','forward')}/${KC.label('p2','left')}/${KC.label('p2','back')}/${KC.label('p2','right')} · ${S.lives} tentativas · J2 ${KC.partnerDevice==='gamepad'?(padConnected?'controle conectado':'conecte um controle padrão e pressione um botão'):'teclado'}`;$('classLabel').textContent=`J1 · ${CLASSES[S.selected].name} · Nv. ${S.level}`;if(S.hero.downed)$('powerLabel').textContent=`J1 caído · ${Math.ceil(S.hero.downTime)}s`;}
for(const button of document.querySelectorAll('[data-mode]'))button.addEventListener('click',()=>{coopSelected=button.dataset.mode==='coop';document.body.classList.toggle('coop-active',coopSelected);document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$('coopOptions').hidden=!coopSelected;$('overlayButton').innerHTML=(coopSelected?'Começar em dupla':'Começar aventura')+' <span>→</span>';});

for(const b of document.querySelectorAll('[data-hero]'))b.addEventListener('click',()=>{S.selected=b.dataset.hero;document.querySelectorAll('[data-hero]').forEach(c=>c.setAttribute('aria-pressed',String(c===b)));$('classHint').textContent=`${CLASSES[S.selected].hp} HP · ${CLASSES[S.selected].skill} desbloqueado no nível 3`;if(S.mode==='menu'){world.remove(S.hero.rig);const a=actor(S.selected,CLASSES[S.selected].color);a.rig.position.set(0,0,4);a.rig.rotation.y=Math.PI;S.hero=a;}});
$('overlayButton').addEventListener('click',()=>{if(S.mode==='paused')pause();else if(['won','lost'].includes(S.mode)){overlay('Escolha seu caminho.','Uma nova classe, uma nova aventura.','Começar aventura','menu');$('overlayEyebrow').textContent='UMA NOVA DIMENSÃO';}else startAdventure();});$('pauseButton').addEventListener('click',pause);function soundLabel(){$('soundButton').textContent=sound?'Som ligado':'Som desligado';$('soundButton').setAttribute('aria-pressed',String(sound));}soundLabel();$('soundButton').addEventListener('click',()=>{sound=!sound;soundLabel();try{localStorage.setItem('salto3d-sound',sound?'on':'off');}catch{}if(sound)soundNote(440,.1);});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();if(S.mode==='playing')pause();notify('A conexão gráfica foi interrompida. Recarregue a página.',60);});
updateKeyHints();S.hp=S.maxHp=5;loadPhase(0);resize();requestAnimationFrame(frame);
// Deterministic browser QA is opt-in; never active on the regular game URL.
if(new URLSearchParams(location.search).get('test')==='1')window.__game={S,CLASSES,THEMES,startAdventure,loadPhase,attack,useSkill,dodge,jump,interact,toggleTarget,cycleTarget,heal,beginGuard,awardXP,enemyHit,damagePlayer,loseLife,pause,floorAt,get partner(){return partner;},get coopSelected(){return coopSelected;},setCoop(value){coopSelected=!!value;},withPlayer,partyAwardXP,checkPortal,qaCoop:{party,applyGamepad,pollGamepad,updatePlayer,updatePartyDowned,updateRevive,teamRespawn},get enemies(){return enemies;},get objects(){return objects;},get items(){return items;},get floors(){return floors;},get projectiles(){return projectiles;},get portal(){return portal;},get boss(){return boss;},get renderer(){return renderer;},get camera(){return camera;},qa:{moveCapsule,moveVertical,segmentHit,blocked,solidBoxes,beginEvade,endEvade,routeInput,get mouseCaptured(){return mouseCaptured;},get padMove(){return padMove;},get evadeHeld(){return evadeHeld;},get keys(){return keys;},updateHero,updateCombat,updateEnemies,updateProjectiles,updateEffects,cameraUpdate,rotateCamera,clearInput,isGuarding,get target(){return target;},beginHeavyCharge,releaseHeavyCharge,requestCombat,animateActor,get comboIndex(){return comboIndex;},get heavyCharge(){return heavyCharge;},get queuedAction(){return queuedAction;},get pendingAttack(){return pendingAttack;},get healTime(){return healTime;},get yaw(){return yaw;},get pitch(){return pitch;},get cameraDistance(){return cameraDistance;}},get cooldowns(){return {attack:attackCooldown,dodge:dodgeCooldown,skill:skillCooldown};}};
})();
